merge: (#196) 자습실 상세 보기 학생 API
team-aliens/DMS-Backend pull request #198
Opened 2022-12-22 09:13 UTC by jeongyoon05

## 작업 내용 설명
- [x] GET /study-rooms/{study-room-id}/students
- [x] QueryStudyRoomStudentUseCase

## 주요 변경 사항
- Security Configuration GET /study-rooms/{study-room-id}/students
- StudyRoomPersistenceAdapter
- SeatTypePersistenceAdapter
- StudentPersistenceAdapter

## 실행 결과
<img width="400" alt="스크린샷 2022-12-22 오후 6 12 08" src="https://user-images.githubusercontent.com/81298238/209099617-a16a06f0-f321-4065-8ad3-ccfc69f7b8e6.png">
<img width="400" alt="스크린샷 2022-12-22 오후 6 12 59" src="https://user-images.githubusercontent.com/81298238/209099787-6d62803c-2995-4644-8d51-e5d72c49be27.png">
<img width="400" alt="스크린샷 2022-12-22 오후 6 13 25" src="https://user-images.githubusercontent.com/81298238/209099876-4aa10954-5275-4d2a-bcdb-f979b261b66e.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #196

2022-12-22 12:44 UTC, softpeanut requested changes
수고하셨습니다

2022-12-22 12:44 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +class QueryStudyRoomStudentUseCase(
p3; 이건 학생이 자습실 상세를 보는 유스케이스이기 때문에 StudentQueryStudyRoomDetailsUseCase로 하는 건 어떤가요?

2022-12-22 12:44 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +            val student = queryStudentPort.queryStudentByIdOrNull(it.studentId)
p3; ~OrNull이든 아니든 하나로 통일해주세요

2022-12-22 12:44 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +        }
```suggestion
        return studentId?.run {
            return studentId == currentUserId
        }
```
다음과 같이 한다면 아래 로직은 굳이 필요 없을 것 같아요

2022-12-22 12:44 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +            val student = queryStudentPort.queryStudentByIdOrNull(it.studentId)
p3; 여기 쿼리가 자리 개수만큼 2개가 추가가 되어서 2N+1 쿼리가 발생할 것 같아요.. 이건 성능에 꽤 큰 영향이 있을 것 같아서 querydsl로 쿼리를 합치는 것이 가능할까요?

2022-12-22 12:44 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
> +    override fun countSeatByStudyRoomId(studyRoomId: UUID) = seatRepository.countByStudyRoomId(studyRoomId)
p1; 이렇게 조회하면 EMPTY나 UNAVAILABLE인 자리도 포함이 됩니다. AVAILABLE한 자리만 조회해야 해요

2022-12-22 12:46 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +            val student = queryStudentPort.queryStudentByIdOrNull(it.studentId)
이건 기존 uuid를 파라미터로 받던 querybyid가 아니라 uuid가 nullable이어서 구현한 메소드가 다릅니다

2022-12-22 12:47 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +            val student = queryStudentPort.queryStudentByIdOrNull(it.studentId)
음....

2022-12-22 12:52 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryStudyRoomStudentUseCase.kt
> +            val student = queryStudentPort.queryStudentByIdOrNull(it.studentId)
차라리 OrNull을 제거하고 메서드 오버로드를 사용하는 것이 일관적이고 알아보기 좋지 않을까요?

2022-12-24 06:23 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/SeatVO.kt
> +package team.aliens.dms.domain.studyroom.dto
p3; 이거는 spi에서 vo 용도로만 사용하니까 spi.vo에 만드는 건 어떤가요?

2022-12-24 06:23 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
> +    private fun isMine(studentId: UUID?, currentUserId: UUID, status: SeatStatus) = studentId?.run {
p3; 여기서 status에 따라서 어떻게 반환되는지 적어주면 더 좋을 것 같아요

2022-12-24 06:23 UTC, softpeanut commented on dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
> +    fun `자신의 자리`() {
p2; status에 대해 저리가 안된 것 같아요

2022-12-24 06:23 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
> +    fun countByStudyRoomIdAndStatus(studyRoomId: UUID, status: SeatStatus): Int
p2; 이거 필요 없는 메서드 아닌가요?

2022-12-24 10:17 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
> +    private fun isMine(studentId: UUID?, currentUserId: UUID, status: SeatStatus) = studentId?.run {
잘 이해가 안됩니다

2022-12-24 15:55 UTC, softpeanut approved these changes

2022-12-24 15:55 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
> +            SeatStatus.AVAILABLE, SeatStatus.IN_USE -> false
studentId가 null인데 IN_USE 상태일 리는 없을 것 같아요
(주석도 지워주세요)

2022-12-25 03:44 UTC, softpeanut approved these changes

2022-12-25 04:58 UTC, merged