merge: (#230)상벌점 부여 api
team-aliens/DMS-Backend pull request #236
Opened 2023-02-17 09:46 UTC by tedsoftj1123

## 작업 내용 설명
- [x] POST /points/history
- [x] ApplyPointUseCase

## 주요 변경 사항
- 상/벌점 부여 api개발
- 기존의 `queryBonusAndMinusTotalPointByStudentGcnAndName`메소드에서 `totalBonus`만 반환하던 코드 변경

## 결과물
<img width="788" alt="image" src="https://user-images.githubusercontent.com/52336493/219609594-e336fd7f-701a-43a6-896a-dba1cab7f448.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/52336493/219610032-d7f05e52-5b16-4090-9fa4-627530dbca59.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #230

2023-02-17 11:42 UTC, rlaisqls requested changes

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointPort.kt
> +    CommandPointPort {
p3 다른 코드와 일관적으로 맞추려면 CommandPointPort가 다른 도메인 관련 port보다 위로 오는 것이 좋을 것 같아요

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/ApplyPointUseCaseTest.kt
> +            .willReturn(pointOptionStub)
p3 가독성을 위해 여기 사이 띄워주시면 좋겠습니다

2023-02-17 11:42 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/ApplyPointWebRequest.kt
> +    val studentIdList: List<UUID>
p2 request field nullable로 해주셔야 validation에서 걸려서 핸들링될 것 같습니다

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/ApplyPointUseCaseTest.kt
> +    fun `학생을_찾을수_없는경우`() {
p3 backtick으로 감싸져 있어서 언더바 사용 안하고 그냥 띄어쓰기하셔도 됩니다.

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/ApplyPointUseCaseTest.kt
> +    fun `상벌점_부여_성공`() {
p3 성공 테스트를 가장 위로 올려주시면 테스트 읽을 때 더 편할 것 같습니다

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +        )?: throw PointOptionNotFoundException
p3 전반적으로 닫는 괄호와 물음표 사이에 띄어쓰기해주세요

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            val student = queryStudentPort.queryStudentById(it)?: throw StudentNotFoundException
p1 이거 map으로 쿼리 각각 날리지 말고 Jpa Repository에 이런식으로 메서드 만들어서 쿼리 한번에 나가게 해야할 것 같아요.. 쿼리가 너무 많이 나가요
```kotlin
    fun findById(ids: List<UUID>): List<Student>
```

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
p1 얘도 뭔가 조치가 필요할 것 같아요. 아니면 아예 위에거랑 묶어서 조인 한 다음에 쿼리 프로젝션 써서 필요한 정보를 VO형태로 가져오는 것도 괜찮을듯 합니다

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/ApplyPointUseCaseTest.kt
> +    @BeforeEach
p3 이 사이 띄워주실 수 있나요

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointPort.kt
> +import java.util.*
p3 wildcard import 쓰면 어떤 클래스를 가져와서 사용했는지 알아보기 힘들어서.. 가능하면 intellij code style에서 use single name import 설정해서 코드 짜주시면 좋을 것 같습니다

2023-02-17 11:42 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +class ApplyPointUseCase(
p2 apply는 부여라기보단 신청이나 적용을 뜻하는 단어인 것 같아요. 좀 더 직관적인 네이밍이었으면 좋곘는데 givePoint 같은 느낌은 어떨까요?

2023-02-17 12:29 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            val student = queryStudentPort.queryStudentById(it)?: throw StudentNotFoundException
네.. 확실히 쿼리가 많이 나가겠네요 수정하겠습니다.

2023-02-18 03:26 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
vo로 가져오려면 pointHistory를 join할때 gcn이 필요한데 쿼리 날리면서 studentJpaEntity에서 gcn을 따로 가공하는게 가능할까요?

2023-02-18 04:51 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +class ApplyPointUseCase(
직관적인 단어가 있는데 굳이 어려운 단어를 택할 필요는 없을 것 같아요.. 그리고 의미상 할당한다는 표현은 조금 부적절하지 않을까요

2023-02-18 05:26 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
따로 가공한다는게 어떤 의미인가요?

2023-02-18 05:33 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
infra에서 studentJpaEntity는 grade랑 classRoom이랑 number가 분리되어있어서  pointHistory를 join할때 gcn을 사용하지 못하니 저 세개를 합치는 과정이 필요할 것 같다는 의미입니다

2023-02-18 05:35 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +class ApplyPointUseCase(
음..그런것 같네요 GivePointUseCase로 수정하겠습니다

2023-02-18 05:38 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
gcn을 학년, 반, 번호로 변환한다음 on절로 동등조인하면 가능하지 않을까요?

2023-02-18 08:05 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ApplyPointUseCase.kt
> +            var (bonusTotal, minusTotal) = queryPointPort.queryBonusAndMinusTotalPointByStudentGcnAndName(it.gcn, it.name)
아 그렇게 하면 되겠네요 수정하겠습니다..

2023-02-18 09:22 UTC, tedsoftj1123 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/ApplyPointWebRequest.kt
> +    val studentIdList: List<UUID>
javax vailtation이 uuid 유효성검사를 하지 못해서 string으로 받고 `UUID.fromString()`을 사용해서 변환하는 형식으로 변경했습니다!

2023-02-19 03:33 UTC, softpeanut requested changes

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/GivePointRequest.kt
> +data class GivePointRequest(
p3; `Grant~~` 어떤가요?

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +    fun execute(givePointRequest: GivePointRequest) {
p4; 이건 그냥 request로 하는게 더 읽기 좋을 것 같아요

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +        schoolId: UUID
p2; schoolId는 굳이 받지 않아도 될 것 같은데요?

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +        val pointList = queryStudentPort.queryStudentsWithPointHistory(givePointRequest.studentIdList)
p2; `~~List`라는 표현은 지양하는 것이 좋아요. 그리고 queryStudentPort를 통해 가져오는 값을 point로 표현하는 것이 어색하네요. 문맥상 `students`라는 표현이 어울리는 것 같습니다. 그리고 queryPort를 통해 가져오는 값들은 별도의 변수로 분리해 명칭을 명확히 하는 것이 좋을 것 같아요

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +                if(it.schoolId != manager.schoolId)
p3; if 문의 실행문은 중괄호를 통해 범위를 정해주세요.

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +                    it.minusTotal += pointOption.score
p3; 이런건 도메인 로직으로 보이는데 분리하는게 좋을 것 같아요.

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +        if(pointList.size != givePointRequest.studentIdList.size)
p1; list의 길이를 검사하는 로직은 생성, 변환 로직이 수행되기 전에 해주세요.

p3; 줄바꿈 해주세용

2023-02-19 03:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    val schoolId: UUID,
p3; schoolId가 꼭 필요한 정보인가요?

2023-02-19 03:33 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                    it.minusTotal ?: 0
p3; 필드를 지정해서 매칭하면 좋을 것 같아요.

2023-02-19 03:33 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +    private fun eqGcn(): BooleanBuilder {
p3; 줄바꿈 해주세요

2023-02-19 03:33 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                        .where(eqGcn())
p1; join걸 때 해당 학교로 걸어야할 것 같네요. 그러면서 학번, 이름이 동일하면서 가장 마지막의 내역을 가져와야할 것 같아요.

2023-02-19 03:33 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/GivePointWebRequest.kt
> +    @field:NotNull
p3; 줄바꿈 해주세요

2023-02-19 13:19 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +        schoolId: UUID
음 디자인상으로는 자기 학교 상벌점 항목밖에 선택할 수 없지만 혹시나 다른 학교의 상벌점 항목이 요청에 올 것을 고려해서 schoolId를 받게 했습니다. 너무 깊히 고려한걸까요..?

2023-02-19 13:33 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    val schoolId: UUID,
이 부분도 위와 비슷하게 다른 학교 학생정보가 요청으로 올때 `SchoolMismatch`예외를 던지도록 하기위해 받았는데`queryStudentsWithPointHistory`메소드에서 schoolId를 받아서 해당학교 학생만 조회되는 방식으로 변경하는게 좋을것 같습니다

2023-02-19 13:37 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                    it.minusTotal ?: 0
넵

2023-02-19 13:50 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +        schoolId: UUID
학교가 동일한지 비교하는 건 도메인 로직으로 취급해야할 것 같아요. 
그런 고려는 좋은 것 같지만 별도의 로직으로 분리하면 더 좋을 것 같아요

2023-02-19 13:51 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    val schoolId: UUID,
위와 동일합니다 !

2023-02-19 14:58 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/GivePointRequest.kt
> +data class GivePointRequest(
음 좋을것 같습니다

2023-02-19 14:59 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GivePointUseCase.kt
> +        val pointList = queryStudentPort.queryStudentsWithPointHistory(givePointRequest.studentIdList)
넵

2023-02-19 15:02 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +        schoolId: UUID
넵

2023-02-19 16:32 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +import java.util.*
p3;  와일드 카드 전부 직접 표기해주세요

2023-02-20 01:52 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +import java.util.*
제가 말한곳 말고도 와일드 카드 많으니깐 전체적으로 코드 한번 확인해주세요

2023-02-20 02:07 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
> +import java.util.*
넵..수정하겠습니다

2023-02-20 02:41 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryManagerPort.kt
> +import java.util.*
;

2023-02-20 02:41 UTC, jeongyoon05 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/GrantPointUseCaseTest.kt
> +import team.aliens.dms.domain.point.spi.*
;

2023-02-20 02:41 UTC, jeongyoon05 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionSchoolMismatchException.kt
> +){
띄어쓰기 하나 해주세요

2023-02-20 02:41 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
> +import java.util.*
;

2023-02-20 02:41 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
> +import java.util.*
;

2023-02-20 02:43 UTC, jeongyoon05 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionSchoolMismatchException.kt
> +){
아니 그냥 지워주세요 중괄호

2023-02-20 02:48 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    var bonusTotal: Int,
p2; var 쓰신 이유는 무엇이죠?

2023-02-20 02:49 UTC, jeongyoon05 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    var bonusTotal: Int,
p3; vo 네이밍도 이상하네요 수정부탁드립니다

2023-02-20 02:52 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
p3; fetch first 사용한 이유는 무엇인가요?

2023-02-20 03:08 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryManagerPort.kt
> +import java.util.*
죄송합니다..

2023-02-20 03:08 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPoint.kt
> +    var bonusTotal: Int,
이전코드에서 수정하지 못한것 같습니다..수정하겠습니다

2023-02-20 03:08 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
어.. 제코드가 아니긴 한데 fetchFirst가 limit(1)이랑 fetch() 한번에 되서 사용하지 않았을까요?

2023-02-20 03:08 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionSchoolMismatchException.kt
> +){
넵

2023-02-20 04:00 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
fetchFirst()를 사용하지 않으면 중복된 데이터가 반환되기 때문에 `NonUniqueResultException`이 발생합니다.

2023-02-20 04:03 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +        fun getNewPointTotalByPointAndPointType(score: Int, pointType: PointType,
정적인 함수가 아닌 인스턴스 함수로 만드는게 더 좋을 것 같아요.

2023-02-20 04:04 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
이 로직을 잘 모르겠어서 이해가 잘 안되네요.. 중복값이 원래 나오는거라 막은거죠? fetch one 을 안쓰고 @softpeanut

2023-02-20 04:10 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
애초에 fetchFirst()를 사용하는 이유는 가장 첫번째 값을 가져오기 위함이고 fetchOne()는 하나의 값을 명시해서 가져오기 위함인데, 상벌점 내역 테이블은 똑같은 학생에게 여러 내역이 존재하기 때문에 가장 첫번째 값을 가져와야 합니다.

2023-02-20 04:10 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +        fun getNewPointTotalByPointAndPointType(score: Int, pointType: PointType,
음 제가 방법을 잘 모르겠어서.. 인스턴스 함수로 만들면 객체를 만들어놓고 update하는 형식으로 사용하면될까요..? 죄송합니다..

2023-02-20 04:11 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
fetchOne()을 할 경우 별도의 limit 조건이 걸리지 않기 때문에 1개 이상의 값이 조회되면 예외가 발생하는 겁니다.

2023-02-20 04:12 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
>              .fetchFirst()
좋습니다

2023-02-20 04:29 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +        fun getNewPointTotalByPointAndPointType(score: Int, pointType: PointType,
저 함수는 PointHistory보다 VO에 있는 것이 어울리는 것 같아서 해당 객체 안에 인스턴스 함수로 만드는게 좋지 않을까요?

2023-02-20 04:33 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +        fun getNewPointTotalByPointAndPointType(score: Int, pointType: PointType,
아 그렇군요 감사합니다..

2023-02-21 02:42 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentWithPointVO.kt
> +    fun getUpdatedPointTotal(type: PointType, score: Int): Pair<Int, Int> {
p3; 이건 그냥 가져오는 것보다 내부에서 계산하는 로직이 있기 때문에 `calculate~`로 표현하면 어떨까요?

2023-02-21 02:42 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
p1; 이거 관련해서 조치가 필요해 보입니다. 
일단 생성일을 비교하는 조건문이 잘못된 것 같아요. 
그리고 동일한 내용을 다른 pr에서도 다루고 있는데 이걸 먼저 끝내고 하는게 더 좋아보여요.

2023-02-21 03:00 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
이게 subquery에 limit을 못걸어서 생각보다 쿼리가 길어진 것 같습니다.. 일단 여기서 on절 안에 있는 조건문들을 따로 함수로 빼고 생성일 비교 부분에서 생기는 문제까지 해결하겠습니다

2023-02-21 03:25 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
일단 최대한 생각해본게 일단 createdAt부분을 학교, 학번, 이름으로 조회해서 가장 최근날짜로 조회하고, 같은 학교이면 동시에 상벌점을 부여했을때 createdAt부분이 겹칠 수 있기 때문에 거기서 학번, 이름으로 조건을 한번 더 추가해서 join해오는 방식인데.. 혹시 다른 방법이 있을까요..? 죄송합니다

2023-02-21 04:20 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
동시에 상벌점을 부여하는 건 여러 학생에게 하나의 상/벌점을 부여하는 건데 가장 최근 날짜를 통해 조인하면 같은 학생에 한해서 하나의 row만 조회될 것 같습니다.
따라서 추가적인 학번, 이름 조회 필요없을 것 같아요.

2023-02-21 04:24 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
p2; max 함수보다 orderBy를 사용해 정렬 후 limit을 거는 것이 더 좋을 것 같아요. 
성능상 큰 차이는 아니지만 실행계획이 한 단계 감소하고, 코드가 간소화됩니다.

2023-02-21 04:30 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
PointHistory는 한 학생마다 가장 최근 내역만 하나씩 조인해야하는게 맞지 않나요??

2023-02-21 04:30 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
근데 추가적으로 저건을 걸지 않으면 on절에 createdAt= ??이런 식으로 나가게 되는데 결국 이러면 다른 정보에 관련없이 createdAt만 같으면 다 가져오니 동시 부여했던 모든 학생이 선택되지 않을까요?

2023-02-21 04:32 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
그렇게 할려고 시도해봤는데 limit은 fetch가 되지 않으면 실행이 안된다고해서... 어쩔 수 없이 저렇게 했습니다.

2023-02-21 04:45 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
```suggestion
                .and(pointHistoryJpaEntity.createdAt.eq(
                select(pointHistoryJpaEntity.createdAt)
                    .from(pointHistoryJpaEntity)
                    .where(
                        pointHistoryJpaEntity.school.id.eq(schoolJpaEntity.id),
                        pointHistoryJpaEntity.studentName.eq(studentJpaEntity.name),
                        eqGcn()
                    )
                    .orderBy(pointHistoryJpaEntity.createdAt.desc())
                    .limit(1)
            ))
```

2023-02-21 04:55 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
이게 코드상에서는 있는데 실제 실행되는 쿼리를 보면 limit이 적용안된 상태로 나가서 위에서 말했 듯 같은 학교 A학생과 B학생한테 동시에 벌점을 줬다면 2개이상 선택되기에 예외가 터집니다
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/52336493/220250842-a5af31ca-c09a-4469-8b5e-a9658583d844.png">

2023-02-21 05:19 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
제가 알기로는 alias를 지정해주면 되는걸로 아는데 안되는 건가요?

```suggestion
                .and(pointHistoryJpaEntity.createdAt.eq(
                Expressions.`as`(
                    select(pointHistoryJpaEntity.createdAt)
                        .from(pointHistoryJpaEntity)
                        .where(
                            pointHistoryJpaEntity.school.id.eq(schoolJpaEntity.id),
                            pointHistoryJpaEntity.studentName.eq(studentJpaEntity.name),
                            eqGcn()
                        )
                        .orderBy(pointHistoryJpaEntity.createdAt.desc())
                        .limit(1), 
                    "recentPointHistory"
                )
            ))
```

2023-02-21 06:25 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
음 그건 아마 mysql의 경우에 그런거고 에초에 jpql에서 만들때 안되는것 같더라구요 시도해봤는데
<img width="970" alt="image" src="https://user-images.githubusercontent.com/52336493/220264266-c6edbf79-45d4-4e6c-bae3-d85bbe5b4cf8.png">
이렇게 에러뜨고 limit이 적용이 안되어있어요

2023-02-21 06:54 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                select(pointHistoryJpaEntity.createdAt.max())
음.. 알겠습니다

2023-02-21 06:58 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
그러네요 잘못 생각했네요 ㅎㅎ..

2023-02-21 06:58 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
근데 저렇게 할거면 저것도 `동일 학생 비교` 함수로 빼는 거 어떤가요?

2023-02-21 07:00 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
음 그냥 저 on절 전체를 함수로 뺏으니까 그냥 사용해도 되지 않을까요?

2023-02-21 07:17 UTC, rlaisqls submitted a review, later dismissed

2023-02-21 07:34 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            )
네 굳이라고 느끼면 안해도 될 것 같습니당

2023-02-21 08:10 UTC, softpeanut approved these changes
LGTM 😄

정말 수고 많으셨습니다 !!

2023-02-21 08:19 UTC, jeongyoon05 approved these changes

2023-02-21 08:20 UTC, jeongyoon05 commented
수고하셨습니다 👍🏿
이게 DMS PR의 참맛 😭

2023-02-21 08:22 UTC, merged