Setting/235 remain available time entity
team-aliens/DMS-Backend pull request #238
Opened 2023-02-17 10:12 UTC by alsdl0629

## 작업 내용 설명
- [x]  잔류 신청 시간 엔티티 세팅

## 주요 변경 사항
잔류 신청 시간
- RemainAvailableTime
- RemainAvailableTimeJpaEntity
- RemainAvailableTimeJpaRepository
- RemainAvailableTimeMapper

## 결과물
![image](https://user-images.githubusercontent.com/103026813/219615727-b2c71f86-998e-4aa3-89f0-e16374239f48.png)

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #235

2023-02-17 11:49 UTC, rlaisqls requested changes

2023-02-17 11:49 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
> +    val startDayOfWalk: DayOfWeek,
p1 오타인 것 같습니다

2023-02-17 11:49 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
p1 erd상으론 VARCHAR(10) 으로 되어있는데, TINYINT로 변경하신 이유가 뭔가요?

2023-02-17 11:49 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +import javax.persistence.*
p3 wildcard import를 사용하면 어떤 클래스를 가져와서 사용하는지 알기 힘들어서, import 항목은 각각 적어주시면 좋을 것 같습니다 (intellij에서 설정할 수 있습니다)

2023-02-17 11:49 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
> +    val startDayOfWalk: DayOfWeek,
JpaEntity에 있는 오타도 수정해주세용

2023-02-17 11:49 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startTime: LocalDate,
p1 LocalDate가 아니라 LocalTime 사용해야할 것 같습니다

2023-02-17 12:05 UTC, alsdl0629 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
enum이 변경될 일이 없을 것 같아서 문자가 아닌 순서로 저장하는 거 어떻게 생각하시나요?

2023-02-17 12:12 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
음 좋네요 erd도 변경해주실 수 있나요?

2023-02-18 04:49 UTC, rlaisqls approved these changes

2023-02-18 18:06 UTC, jeongyoon05 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
순서로 저장하면 추후에 DB 에서 값을 볼 일이 생겼을때 불편할수도 있을것 같습니다. 그래서 그냥 문자열로 넣는게 좋을것 같습니다. 어떻게 생각하시나요?
@alsdl0629 @rlaisqls

2023-02-19 01:38 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
변경될 특성이 없는 속성인건 확실해서 어떤 방법이 특별한 장점을 가지고 있다고 말할 수 있을지 모르겠어요. 하지만 구현이나 저장에 드는 비용이 크게 차이나는게 아니라서, 말씀해주신 문제 고려하면 그냥 안전하게 String으로 하는게 나을 것 같긴 하네요.

2023-02-19 03:54 UTC, alsdl0629 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainAvailableTimeJpaEntity.kt
> +    val startDayOfWalk: DayOfWeek,
문자열을 저장하는 걸로 변경하겠습니다.

2023-02-19 13:49 UTC, softpeanut approved these changes
LGTM

2023-02-19 14:49 UTC, rlaisqls approved these changes

2023-02-19 14:55 UTC, merged