merge: (#245) 학생목록조회 상벌점 필터 추가
team-aliens/DMS-Backend pull request #246
Opened 2023-02-20 07:11 UTC by tedsoftj1123

## 작업 내용 설명
- [x] 기존 학생목록 UseCase에서 상/벌점 필터링 기능 추가

## 주요 변경 사항
- `QueryStudentsUseCase`
- `StudentPersistenceAdapter`

## 결과물
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/52336493/220036787-2df327db-d145-447a-93d7-7882c578e884.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #245

2023-02-20 08:23 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +    fun execute(name: String?, sort: Sort, filterType: String?, minPoint: Int?, maxPoint: Int?): QueryStudentsResponse {
p3; 인자가 많아서 줄 나눠주시면 가독성이 더 좋아질 것 같아요

2023-02-20 08:23 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +        val pointFilterType = if(filterType != null) {
p4; ?.let 쓰면 좀 더 간결하게 표현할 수 있을 것 같아요

2023-02-20 08:23 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +            name, sort, manager.schoolId, pointFilterType, minPoint, maxPoint
p3; 인자 많은 함수 호출할때는 parameter name 같이 적고, 여러 줄로 나눠주세용..

2023-02-20 08:26 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +            name, sort, manager.schoolId, pointFilterType, minPoint, maxPoint
넵

2023-02-20 08:37 UTC, rlaisqls commented
테스트 커버리지 떨어진거 수정해주세용

2023-02-20 08:54 UTC, rlaisqls requested changes

2023-02-20 08:54 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                    select(pointHistoryJpaEntity.createdAt.max())
p1; 상벌점읊 여러 유저에 일괄부여한 경우엔 createdAt이 중복일 수 있어서, (학번과 이름이 같은) 한 학생에 대한 최신 내역을 가져오도록 쿼리를 수정해여할 것 같아요

2023-02-20 08:58 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                    select(pointHistoryJpaEntity.createdAt.max())
넵

2023-02-20 09:30 UTC, softpeanut requested changes

2023-02-20 09:30 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
> +        maxPoint: Int?
p2; 이거 3개를 하나의 객체로 표현할 수 있을 것 같아요. 인자가 많아지는 건 레거시의 길입니다.

2023-02-20 09:30 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +        }
p2; 이런 로직 또한 위에 말한 객체에서 init 함수를 통해 표현하면 좋을 것 같아요.

2023-02-20 09:30 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/InvalidFilterRequestException.kt
> +object InvalidFilterRequestException : DmsException(
p3; 객체 이름에서 뭐하는 건지 표현이 안된 것 같아요.

2023-02-20 09:30 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                        .where(eqGcn())
p1; 이 조건문에 학번 관련된 조건만 있다면 모든 학교에 같은 학번인 학생을 대상으로 조회가 됩니다. 해당 조건문 확인해주세요.

그리고 해당 내용(상벌점 내역을 가져오는 것)은 많은 곳에서 사용되기 때문에 별도의 함수로 분리하는 것이 좋을 것 같아요.

2023-02-20 09:30 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +    }
p2; 해당 함수도 다른 곳과 겹치는 것 같아요.

2023-02-20 10:58 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                        .where(eqGcn())
이 서브쿼리 자체를 함수로 분리하라는 말씀이신가요?

2023-02-20 11:02 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
> +        maxPoint: Int?
넵..수정하겠습니다.

2023-02-20 13:49 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                        .where(eqGcn())
또는 조인을 거는 부분을 하나로 묶어도 좋을 것 같아요

2023-02-20 13:59 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +                        .where(eqGcn())
넵 알겠습니다

2023-02-21 03:27 UTC, rlaisqls approved these changes

2023-02-21 10:37 UTC, rlaisqls approved these changes

2023-02-22 02:38 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/StudentPointFilter.kt
> +    }
```suggestion
       init(filterType: PointFilterType?, minPoint: Int?, maxPoint: Int?): StudentPointFilter? {
            return filterType?.let {
                if(maxPoint == null || minPoint == null || maxPoint < minPoint) {
                    throw InvalidPointFilterRangeException
                }

                StudentPointFilter(
                    filterType = filterType,
                    maxPoint = maxPoint,
                    minPoint = minPoint
                )
            }
        }
```

2023-02-22 02:38 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/StudentPointFilter.kt
> +data class StudentPointFilter (
`PointFilter`가 더 좋을 것 같습니다

2023-02-22 02:38 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
> +            studentPointFilter
p3; 여긴 필드 명시가 빠진 것 같아요

2023-02-22 07:35 UTC, softpeanut approved these changes
LGTM 👍

2023-02-22 13:38 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            .join(studentJpaEntity.user, userJpaEntity).fetchJoin()
기존의 학생목록 조회에서 n+1이 발생하는것같아 일단 해결하긴 했는데.. 한번 봐주시면 좋을 것 같습니다

2023-02-22 14:05 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            .join(studentJpaEntity.user, userJpaEntity).fetchJoin()
n+1이 user에 발생했던건가요?

2023-02-22 14:13 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            .join(studentJpaEntity.user, userJpaEntity).fetchJoin()
네 user부분에서 발생하더라구요

2023-02-22 14:23 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
> +        )
근데 이거 조건 점수 입력하지 않은 경우가 아니라 범위 잘못된 경우 아닌가요?
그리고 assertAll인데 두 assert문을 한 Excutable 스코프로 묶으면 약간 의미가 없어지는 것 같긴 하네요

2023-02-22 14:26 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +            .join(studentJpaEntity.user, userJpaEntity).fetchJoin()
mapper에서 조회하는거때문에 그런가보네요.... 다른 쿼리 짤때도 유의해야겠네여

2023-02-22 14:32 UTC, tedsoftj1123 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
> +        )
아 그렇네요 분리하도록 하겠습니다

2023-02-23 02:20 UTC, jeongyoon05 approved these changes

2023-02-23 02:53 UTC, merged