merge: (#249) 상벌점 부여 취소 api
team-aliens/DMS-Backend pull request #250
Opened 2023-02-21 01:47 UTC by rlaisqls

## 작업 내용 설명
- [x]  CancelGrantedPointUseCase
- [x] DELETE /points/history/{point-history-id}

## 주요 변경 사항
- 상벌점 부여 취소 api
- domain 모듈에 있는 PointHistory model에 취소 내역을 반환하는 메서드를 만들었습니다.

## 결과물
<img src="https://user-images.githubusercontent.com/81006587/220226678-2fc2a8fd-ca09-4fba-94ef-730d8050529c.png" height=150px>

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #249

2023-02-21 12:58 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
> +    @DeleteMapping("/history/{point-history-id}")
p2; 이거 지금 요구사항이 기존 내역은 삭제하고 새롭게 취소 내역을 추가해야 하는데 `DELETE`는 어울리지 않는 것 같아요.
`PUT`은 어떤가요?

2023-02-21 12:58 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +    fun canceledHistory(): PointHistory {
p2; `candeled`라는 표현보다 `calcel`이 어울리는 것 같아요.

2023-02-21 12:58 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +                (if (pointType == PointType.MINUS) pointScore else 0)
```suggestion
        fun calculateTotalPoint(): Pair<Int, Int> {
            return if (this.pointType == PointType.BONUS) {
                Pair(this.bonusTotal + this.pointScore, this.minusTotal)
            } else {
                Pair(this.bonusTotal, this.minusTotal + pointScore)
            }
        }
```

2023-02-21 15:30 UTC, tedsoftj1123 requested changes

2023-02-21 15:30 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
> +    private fun calculateTotalPoint(): Pair<Int, Int> {
p3; `calculateCanceledPointTotal` 어떤가요?

2023-02-21 15:30 UTC, tedsoftj1123 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
> +    }
p2; 이게 securityConfig에선 DELETE로 매핑된것 같은데 통일해야될 것 같아요

2023-02-21 15:30 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointHistoryErrorCode.kt
> +    POINT_HISTORY_CAN_NOT_CANCEL(400, "Point History Can Not Cancel")
p3; 음 상벌점내역을 취소할 수 없다 보다 잘못된 상벌점내역이라고 INVALID_POINT_HISTORY어떤가요? 저걸 사용한다면 cancel을 수동태인 canceled로 바꾸면 좋을것 같아요

2023-02-22 00:29 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointHistoryErrorCode.kt
> +    POINT_HISTORY_CAN_NOT_CANCEL(400, "Point History Can Not Cancel")
invalid는 수행하려는 동작과 내역 자체가 유효하지 않다는 의미를 내포하고 있는 것 같아서 can not으로 작명했는데, 뒤에 ed를 붙여야 하는 이유가 뭔지.. 잘 모르겠네요. 철저히 따질 필욘 없지만 영문법상으로는 동사 원형이 오는게 맞긴 합니다

2023-02-22 05:35 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointHistoryErrorCode.kt
> +    POINT_HISTORY_CAN_NOT_CANCEL(400, "Point History Can Not Cancel")
넵 알겠습니다

2023-02-22 05:38 UTC, tedsoftj1123 approved these changes

2023-02-22 07:03 UTC, softpeanut approved these changes

2023-02-22 07:20 UTC, merged