merge: (
team-aliens/DMS-Backend pull request #253
Opened 2023-02-21 09:29 UTC by tedsoftj1123

## 작업 내용 설명
- [ ] 
- [ ] 

## 주요 변경 사항
- 
- 

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #

2023-02-21 09:58 UTC, rlaisqls requested changes

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
> +        if(queryPointOptionPort.existByNameAndSchoolId(request.name, manager.schoolId)) {
p4 if 뒤에 띄워주시면 좋을 것 같아요

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
> +            { assertThat( createPointOptionUseCase.execute(requestStub)).isNotNull },
p2 현재 코드는 assertThat 메서드의 반환값이 null인지를 확인하고 있는 것 같아요.
그리고 반환값이 null인지 확인하는건 의미 없는 테스트인 것 같습니다. (코틀린이라서 어차피 notnull이니까요...)
save 메서드의 반환값을 stub으로 지정해서 그 값이 일치하는지 확인하는지 확인하는 테스트면 좀 더 의미를 가질 것 같아요

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
> +            { assertDoesNotThrow {createPointOptionUseCase.execute(requestStub)} }
p2 useCase를 두번 실행시키면서까지 asserDoesNotThrow를 검사할 필욘 없을 것 같습니다. (Exceptoin 발생하면 테스트도 어차피 같이 깨지니까요...)

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
> +
p3 여기 when then 주석 빠졌습니다

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +    }
p2 이거랑 schoolId 그냥 1, 2로 이름 짓지 말고 스텁 용도에 따라 작명해주시면 좋을 것 같습니다. 아래 스텁은 otherSchoolId, otherSchoolPointOptionStub 이런 식으로요!

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +    @Test
p3 여기 사이 줄바꿈은 좀 신경쓰이네요

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +}
p3 여기 사이 빈 두줄 없애주세요..

2023-02-21 09:58 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
> +import java.util.*
p2 wildcard import?

2023-02-21 09:58 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
> +    }
p2 작성하신 로직에서 id만 필요한건 알지만 통일성 및 확장성을 위해서 그냥 PointOption 도메인 모델 반환하도록 하는게 자연스러울 것 같습니다

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +import java.util.*
p2 wildcard import??

2023-02-21 09:58 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
> +    private val securityPort: PointSecurityPort = mockk()
p4 두줄씩 띄워진거 한번씩 검토하시면 좋을 것 같아요. 린트 도입의 필요성이네요...

2023-02-21 09:59 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
> +import java.util.*
반성하겠습니다..

2023-02-21 10:00 UTC, tedsoftj1123 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +    }
넵

2023-02-21 10:01 UTC, tedsoftj1123 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +import java.util.*
죄송합니다..

2023-02-21 10:32 UTC, rlaisqls commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +import java.util.*
죄송하진 않으셔도 됩니다...ㅠㅠ

2023-02-21 10:39 UTC, tedsoftj1123 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
> +import java.util.*
😓

2023-02-21 10:39 UTC, tedsoftj1123 commented on dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
> +    private val securityPort: PointSecurityPort = mockk()
앞으로 검토를 확실히 하도록 하겠습니다..

2023-02-21 10:45 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
> +            )
p3 여기 탭 한번씩 덜 해야할 것 같아요

2023-02-21 10:49 UTC, rlaisqls approved these changes
사실 줄간격 신경쓰이는 부분이 있긴 한데.. 기간이 기간이다보니 너무 심각한거 아니면 주 흐름 및 동작여부 위주로 리뷰하고 넘어가도 괜찮을 것 같아요.

2023-02-21 10:52 UTC, rlaisqls approved these changes

2023-02-21 16:12 UTC, softpeanut approved these changes
코드는 괜찮아 보이지만 생성과 삭제를 한 번에 해야하는 이유가 있었나요?
17개면 적은 양이 아니라 가능하면 잘게 쪼개면 좋을 것 같아요.

2023-02-21 16:17 UTC, tedsoftj1123 reviewed
코드가 단순해 변경사항이 없을 것 같아 한번에 했는데 너무 많아질걸 고려하지 못한 것 같습니다. 다음부턴 주의하겠습니다..

2023-02-21 16:22 UTC, tedsoftj1123 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt
> +}
음 그 방법도 좋고 이부분은 일단 string으로 받고 usecase에서 valueOf로 변환해 사용하는 방법도 있을 것 같은데 어떻게 생각하시나요?

2023-02-21 16:29 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt
> +}
변환은 비즈니스 로직보단 validation 부분에 가까워서 사전에 차단해도 좋을 것 같아요

2023-02-22 06:10 UTC, tedsoftj1123 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt
> +}
근데 저 webPointType이 presentation계층에 있어서 저 enum안에서 바로 변경할 수 없을 것 같은데.. 그냥 valueOf 사용하는것은 어떤가요?

2023-02-22 06:57 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt
> +}
일단은 그렇게 하죠

2023-02-22 07:33 UTC, merged