merge: (#248) 잔류 신청 시간 보기 API
team-aliens/DMS-Backend pull request #258
Opened 2023-02-21 15:25 UTC by alsdl0629

## 작업 내용 설명
- [X] GET /remains/available-time
- [X] QueryRemainAvailableTimeUseCase

## 주요 변경 사항
- 잔류 신청 시간 보기 API

## 결과물
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/103026813/220386418-6fa9d2a7-be28-493d-9d08-ba368ddb15ad.png">

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [X] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #248

2023-02-21 15:48 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainAvailableTimeNotFound.kt
> +object RemainAvailableTimeNotFound : DmsException(
p3; Exeption붙여주세요

2023-02-21 15:48 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCase.kt
> +        }
p3; 이부분 도메인 로직으로 분리되면 좋을 것 같아요

2023-02-21 15:48 UTC, tedsoftj1123 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
> +    REMAIN_AVAILABLE_TIME_CAN_NOT_ACCESS(403, "Remain Available Time Can Not Access"),
p4; 이거 CAN_NOT_ACCESS_REMAIN_AVAILABLE_TIME어떤가요?

2023-02-21 16:21 UTC, softpeanut approved these changes

2023-02-21 16:31 UTC, alsdl0629 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
> +    REMAIN_AVAILABLE_TIME_CAN_NOT_ACCESS(403, "Remain Available Time Can Not Access"),
여기는 변경하지 않아도 괜찮을 것 같습니다

2023-02-22 01:36 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +}
p2 도메인 서비스는 여러 애그리거트가 필요한 계산 로직이나 한 애그리거트에 넣기에 다소 복잡한 계산 로직 등을 넣어놓는 역할인걸로 알고있는데요... RemainAvaliableTime 하나만 받아서 날짜 계산하는 로직은 도메인 모델에다가 member function으로 넣는게 더 간결하지 않을까요?

2023-02-22 02:29 UTC, rlaisqls requested changes

2023-02-22 02:29 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +        }
```suggestion
        if (dayOfWeek == avliableTime.startDayOfWeek && now < availableTime.startTime) {
            return false
        }
        
       if (dayOfWeek == avliableTime.endDayOfWeek && now < availableTime.endTime) {
            return false
        }
```
p1 기존 코드는 잔류 신청 가능 시작요일과 종료요일이 다른 경우에 에러날 것 같습니당

2023-02-22 09:09 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
> +    fun isAccessible(): Boolean {
p2 isAccessible보다 isAvailable이 더 적절한 것 같아요

2023-02-22 09:22 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +        }
조건 하나로 통일시켜서 조회해야 할 것 같습니다.

2023-02-22 09:33 UTC, alsdl0629 commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +        }
조건문을 하나로 줄이라는 말씀이신 건가요?

2023-02-22 09:46 UTC, rlaisqls approved these changes

2023-02-22 15:40 UTC, rlaisqls commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +        }
이렇게 조회하면 목요일 10시에 신청 가능해지는거 아닌가요? `dayOfWeek == avliableTime.startDayOfWeek`이나 `dayOfWeek == avliableTime.endDayOfWeek`에 안걸리면 false로 return될 일이 없으니까요

1. 요일이 범위 밖인 경우 false
2. 시작 요일인 경우 시작 시간 이전이면 false
3. 종료 요일인 경우 종료 시간 이후면 false

이렇게 하면 딱 깔끔하게 조건문 3개로 정리될 것 같아요

2023-02-22 16:16 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/service/CheckAccessibleRemainAvailableTimeService.kt
> +        }
현재 로직으로는 시작 요일 전에도 가능할 것 같네요.
은빈님이 말씀해주신 3가지로 나누어서 처리하도록 변경해야할 것 같아요.

2023-02-23 02:26 UTC, jeongyoon05 approved these changes

2023-02-23 04:44 UTC, softpeanut requested changes

2023-02-23 04:44 UTC, softpeanut commented on dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
> +        }
p2; 하나의 함수에 return 문이 너무 많은 것 같습니다.
조건문을 별도의 함수로 분리해 용도를 쉽게 파악하고 코드를 간결하게 만들면 좋을 것 같습니다.

ex)
```suggestion
        if (isOutOfRangeDay() || isBeforeStartTime() || isAfterEndTime()) {
            return false
        }
```

2023-02-23 08:21 UTC, softpeanut approved these changes
LGTM 😃

2023-02-23 08:22 UTC, merged