merge: (#262) 잔류 신청 항목 목록 보기 API
team-aliens/DMS-Backend pull request #266
Opened 2023-02-22 11:32 UTC by alsdl0629

## 작업 내용 설명
- [ ] GET /remains/options
- [ ] QueryRemainOptionsUseCase

## 주요 변경 사항
- 잔류 신청 항목 목록 보기 API

## 결과물
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/103026813/220608102-3f3bc512-cbf3-4d3a-863c-6f5440209719.png">

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [X] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #262

2023-02-22 11:40 UTC, rlaisqls approved these changes

2023-02-22 11:40 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
> +        }
```suggestion
    override fun queryAllRemainOptionBySchoolId(schoolId: UUID) =
        remainOptionRepository.findAllBySchoolId(schoolId)
            .map { remainOptionMapper.toDomain(it)!! }
```
p3 이거 줄바꿈 좀 애매한데 이렇게 바꾸는거 어떠신가요?

2023-02-22 13:23 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryRemainStatusPort.kt
> +}
p4; 이 포트 자체가 remain도메인에서 사용되는것이니 앞의 Remain은 생각하는게 어떨까요?

2023-02-22 13:23 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
> +}
p4; 여기 줄바꿈 하면 좋을 것 같아요

2023-02-22 13:26 UTC, alsdl0629 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryRemainStatusPort.kt
> +}
네

2023-02-22 13:27 UTC, alsdl0629 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
> +}
나중에 다중상속 받을 때 바꿔도 될 것 같습니다

2023-02-22 16:22 UTC, softpeanut approved these changes
LGTM

2023-02-22 16:26 UTC, softpeanut requested changes

2023-02-22 16:26 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
> +                queryRemainOptionPort.queryRemainOptionById(it.remainOptionId)?.title
p1; 여기서 쿼리 날리지 말고 아래처럼 구현하는게 좋을 것 같아요.

```suggestion
remainOptions.find { it.id == remainStatus.remainOptionId }?.title
```

2023-02-22 16:28 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/QueryRemainOptionsResponse.kt
> +    val selectedOption: String?,
p3; 음 이거 appliedRemainOption으로 바꾸면 어떨까요?

2023-02-22 17:00 UTC, alsdl0629 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
> +                queryRemainOptionPort.queryRemainOptionById(it.remainOptionId)?.title
넵

2023-02-23 02:04 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
> +                it.id == remainStatus!!.remainOptionId
```suggestion
                it.id == remainStatus?.remainOptionId
```

2023-02-23 11:31 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
> +interface RemainStatusPort : CommandRemainStatusPort, QueryRemainStatusPort {
p4; 여기 엔터한번 쳐주면 좋을것 같아요

2023-02-24 00:18 UTC, softpeanut approved these changes

2023-02-24 01:55 UTC, merged