merge: (#269) 잔류 신청 api
team-aliens/DMS-Backend pull request #272
Opened 2023-02-23 11:11 UTC by rlaisqls

## 작업 내용 설명
- [x] ApplyRemainUseCase
- [x] PUT remains/{remain-option-id}

## 주요 변경 사항
- 잔류 신청 api

## 결과물
![image](https://user-images.githubusercontent.com/81006587/220639266-d30e7e3f-7ef0-4a59-a7e6-53afdb64a8bb.png)

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #269

2023-02-23 11:26 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        val remainOption = queryRemainOptionPort.queryRemainOptionById(remainOptionId) ?: throw RemainOptionNotFoundException
p3; 음 디자인상으론 자기 학교의 항목만 신청할 수밖에 없긴한데 따로 학교에대한 검사는 하지 않아도 될까요?

2023-02-23 12:22 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        val remainOption = queryRemainOptionPort.queryRemainOptionById(remainOptionId) ?: throw RemainOptionNotFoundException
해야겠네요...

2023-02-23 13:43 UTC, alsdl0629 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainCanNotAppliedException.kt
> +)
p1 여기 에러 코드랑 예외 이름이랑 다른 것 같아요

2023-02-24 00:48 UTC, softpeanut requested changes

2023-02-24 00:48 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        if (remainOption.schoolId != currentUser.schoolId) {
p3; 시간보다 학교 비교를 먼저 하면 좋을 것 같아요

2023-02-24 00:48 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        commandRemainStatusPort.saveRemainStatus(
p1; 기존 신청 내역은 지워야 할 것 같아요

2023-02-24 01:22 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        commandRemainStatusPort.saveRemainStatus(
studentId랑 OneToOne으로 mapsId라 기존 신청 있는 경우엔 수정되어서 지우는 쿼리를 꼭 날릴 필요는 없을 것 같아요

2023-02-24 04:21 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
> +        commandRemainStatusPort.saveRemainStatus(
아 식별관계 였군요

2023-02-24 04:22 UTC, softpeanut approved these changes

2023-02-24 04:27 UTC, alsdl0629 approved these changes

2023-02-24 04:47 UTC, merged