merge: (#273) 상벌점 항목 변경
team-aliens/DMS-Backend pull request #274
Opened 2023-02-24 05:24 UTC by tedsoftj1123

## 작업 내용 설명
- [x] PATCH /points/options/{point-option-id}
- [x] UpdatePointOptionUseCase

## 주요 변경 사항
- 상벌점 항목 변경 api개발
- path value 유효성 검사 추가

## 결과물
<img width="793" alt="image" src="https://user-images.githubusercontent.com/52336493/221098971-c2eede4f-209c-434a-8648-956b51b2a7c4.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #273

2023-02-24 05:32 UTC, rlaisqls approved these changes

2023-02-24 06:46 UTC, jeongyoon05 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/UpdatePointOptionWebRequest.kt
> +    @field:NotNull
제가 알기론 문자열은 전부 @NotBlank 사용했는데 여기는 @NotNull 사용한 이유가 있나요?

2023-02-24 06:54 UTC, tedsoftj1123 commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/UpdatePointOptionWebRequest.kt
> +    @field:NotNull
음..후에 enum으로 변환되기에 notnull을 사용했지만 결국 요청받는 타입은 string이니 `@NotBlank`를 사용하는게 좋을것 같네요 수정하도록 하겠습니다

2023-02-24 07:10 UTC, rlaisqls requested changes

2023-02-24 07:10 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
> +                type = PointType.valueOf(request.type)
p2 근데 이거 여기서 에러나면 500 터지는거 아닌가요?

2023-02-24 07:45 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
> +                type = PointType.valueOf(request.type)
아 그러네요.. 수정하겠습니다

2023-02-24 08:39 UTC, rlaisqls approved these changes

2023-02-24 08:43 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
> +                type = PointType.valueOf(request.type)
엄.. save 메서드 타고가서 500이라는 뜻이 아니라 IllegalArgumentException 떠서 500일 수 있을 것 같다는 의미였어요. 근데 WebEnum으로 걸러주니까 상관 없겠네요...ㅎ

2023-02-25 03:55 UTC, tedsoftj1123 commented on dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/UpdatePointOptionRequest.kt
> +    val type: String,
넵

2023-02-25 05:23 UTC, softpeanut approved these changes
LGTM

2023-02-25 06:02 UTC, merged