merge: (#303) Prod Dev 환경분리
team-aliens/DMS-Backend pull request #333
Opened 2023-03-08 14:55 UTC by alsdl0629

## 작업 내용 설명
- [X] prod dev cd 분리

## 주요 변경 사항
- dev-cd.yml 추가

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #303

2023-03-08 22:22 UTC, rlaisqls approved these changes

2023-03-09 01:33 UTC, softpeanut requested changes

2023-03-09 01:33 UTC, softpeanut commented on .github/workflows/dev-cd.yml
> +            docker run -d --name dms-dev -p ${{ secrets.APPLICATION_PORT }}:8080 --env-file .env ${{ secrets.DOCKER_DEV_IMAGE }}
APPLICATION_PORT가 같으면 안될 것 같은데

2023-03-09 02:47 UTC, rlaisqls commented on .github/workflows/dev-cd.yml
> +            docker run -d --name dms-dev -p ${{ secrets.APPLICATION_PORT }}:8080 --env-file .env ${{ secrets.DOCKER_DEV_IMAGE }}
다른 ec2에다 올리는거라서 괜찮지 않을까요?

2023-03-09 04:35 UTC, jeongyoon05 approved these changes

2023-03-11 09:08 UTC, merged