merge: (#372) 태그 추가 api
team-aliens/DMS-Backend pull request #375
Opened 2023-03-23 10:54 UTC by tedsoftj1123

## 작업 내용 설명
- [x] POST /tags
- [x] CreateTagUseCase

## 주요 변경 사항
- CreateTagUseCase

## 결과물
<img width="742" alt="image" src="https://user-images.githubusercontent.com/52336493/227181939-21a7ab60-01be-43b1-81ca-fc6a35c359f5.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [x] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #372

2023-03-23 11:23 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/CreateTagWebRequest.kt
> +)
nullable 타입으로 해야 validation 걸릴 것 같습니다

2023-03-23 13:21 UTC, alsdl0629 approved these changes

2023-03-23 13:23 UTC, rlaisqls approved these changes

2023-03-23 23:33 UTC, softpeanut requested changes

2023-03-23 23:33 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCase.kt
> +        if (queryTagPort.existsByName(name)) {
조회할 때 학교 id도 함께 조회해야 합니다

2023-03-23 23:33 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
> +    fun createTag(@RequestBody @Valid webRequest: CreateTagWebRequest): CreateTagWebResponse {
성공시 반환되는 status가 잘못된 것 같아요

2023-03-24 00:02 UTC, softpeanut approved these changes

2023-03-25 08:21 UTC, merged