merge: (#367) 학생 태그 부여 API
team-aliens/DMS-Backend pull request #377
Opened 2023-03-24 09:23 UTC by alsdl0629

## 작업 내용 설명
- [ ] post /tags/students
- [ ] GrantTagUseCase

## 주요 변경 사항
- 학생 태그 부여 API

## 결과물
![image](https://user-images.githubusercontent.com/103026813/227478215-92a5f9c8-e509-4b41-b9bc-5587fde4a358.png)

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [X] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #367

2023-03-24 11:44 UTC, rlaisqls approved these changes

2023-03-24 12:07 UTC, jeongyoon05 approved these changes

2023-03-25 04:06 UTC, softpeanut requested changes

2023-03-25 04:06 UTC, softpeanut commented on dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/GrantTagUseCase.kt
> +        if (request.studentIds.count() != students.count()) {
```suggestion
        if (students.map { it.id }.containsAll(request.studentsIds)) {
```

2023-03-25 04:47 UTC, softpeanut approved these changes

2023-03-25 08:41 UTC, merged