merge: (#390) tag 필터링 추가
team-aliens/DMS-Backend pull request #391
Opened 2023-03-27 16:23 UTC by tedsoftj1123

## 작업 내용 설명
- [x] 학생목록 조회api에서 태그 필터링 추가

## 주요 변경 사항
- QueryStudentsUseCase
- StudentPersistenceAdapter

## 결과물
<img width="837" alt="image" src="https://user-images.githubusercontent.com/52336493/228002996-61b63f1c-359f-4b3d-a088-d72261d5a583.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #390

2023-03-28 00:27 UTC, rlaisqls requested changes

2023-03-28 00:27 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +        }
이거 서브쿼리로 빼지 말고 join해서 where문으로 넣으면 안되나요?

2023-03-28 00:39 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +        }
join 해서 where를 사용하면 학생은 상관없이 조회되고 그 학생에대한 태그만 조회되지 않아서 필터링이 안될것 같습니다

2023-03-28 01:07 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
> +        }
...? join하면 where문 했을때 같이 걸려서 안보이는데 혹시 테스트 해보셨나요?

2023-03-28 06:57 UTC, rlaisqls reviewed
```kotlin
    override fun queryStudentsByNameAndSortAndFilter(
        name: String?,
        sort: Sort,
        schoolId: UUID,
        pointFilter: PointFilter,
        tagIds: List<UUID>?
    ): List<StudentWithTag> {
        return queryFactory
            .selectFrom(studentJpaEntity)
            .join(studentJpaEntity.room, roomJpaEntity)
            .join(studentJpaEntity.user, userJpaEntity)
            .join(userJpaEntity.school, schoolJpaEntity)
            .leftJoin(pointHistoryJpaEntity)
            .on(eqStudentRecentPointHistory())
            .leftJoin(studentTagJpaEntity)
            .on(studentJpaEntity.id.eq(studentTagJpaEntity.student.id))
            .leftJoin(tagJpaEntity)
            .on(studentTagJpaEntity.tag.id.eq(tagJpaEntity.id))
            .where(
                nameContains(name),
                pointTotalBetween(pointFilter),
                schoolEq(schoolId),
                tagIdsIn(tagIds)
            )
            .orderBy(
                sortFilter(sort),
                studentJpaEntity.grade.asc(),
                studentJpaEntity.classRoom.asc(),
                studentJpaEntity.number.asc()
            )
            .transform(
                groupBy(studentJpaEntity.id)
                    .list(
                        QQueryStudentsWithTagVO(
                            studentJpaEntity.id,
                            studentJpaEntity.name,
                            studentJpaEntity.grade,
                            studentJpaEntity.classRoom,
                            studentJpaEntity.number,
                            roomJpaEntity.number,
                            studentJpaEntity.profileImageUrl,
                            studentJpaEntity.sex,
                            list(tagJpaEntity)
                        )
                    )
            )
            .map {
                StudentWithTag(
                    id = it.id,
                    name = it.name,
                    grade = it.grade,
                    classRoom = it.classRoom,
                    number = it.number,
                    roomNumber = it.roomNumber,
                    profileImageUrl = it.profileImageUrl,
                    sex = it.sex,
                    tags = it.tags
                        .map { tag ->
                            tagMapper.toDomain(tag)!!
                        }
                )
            }
    }

    private fun nameContains(name: String?) = name?.run { studentJpaEntity.name.contains(this) }

    private fun tagIdsIn(tagIds: List<UUID>?) =
        if (tagIds?.isNotEmpty() == true) studentTagJpaEntity.tag.id.`in`(tagIds) else null
```

코드 이런식으로 해보는거 어떨까여

2023-03-28 13:54 UTC, softpeanut commented
결과 테스트 해보고 잘 나오면 괜찮을 것 같아요

2023-03-29 00:47 UTC, tedsoftj1123 commented
이렇게 하면 학생 필터링은 되긴 하는데 tag를 join할때 필터에 있는 태그들만 가져오는거라 필터에 해당되는 태그 말고는 조회가 안되서 tag부분은 subquery로 조인해야될것 같은데 어떻게 생각하시나요

2023-03-29 00:52 UTC, rlaisqls reviewed
음 맞네요.. tag 부분은 서브쿼리가 최선인 것 같아요. eqTag()만 조건문으로 바꿔주심 좋을듯 합니다

2023-03-29 01:35 UTC, rlaisqls approved these changes

2023-03-29 06:21 UTC, merged