merge: (#397) 태그 수정 시 중복 예외 제거
team-aliens/DMS-Backend pull request #398
Opened 2023-03-28 13:27 UTC by alsdl0629

## 작업 내용 설명
- [X] 태그 수정 시 중복 예외 제거

## 주요 변경 사항
- 중복 예외 제거

## 결과물
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/103026813/228251893-b9c213b4-9f5b-4bb6-8d56-f2b07272ebd5.png">

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [X] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #397

2023-03-28 13:35 UTC, softpeanut approved these changes
중복 예외 왜 제거하나요?

2023-03-28 14:29 UTC, tedsoftj1123 approved these changes

2023-03-28 14:43 UTC, rlaisqls requested changes

2023-03-28 14:43 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
> -        }
이거 없애지 말고 newName이랑 tag.name 다른 경우에 exists 조회해서 예외 던지는걸로 바꿔야할 것 같은데요

2023-03-28 14:45 UTC, rlaisqls commented on dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
> +
이거 이렇게 되면 색깔만 바꾸는경우에 똑같이 409뜨는거 아니에요?

2023-03-29 04:25 UTC, rlaisqls approved these changes

2023-03-29 04:56 UTC, merged