merge: (#425) logging추가
team-aliens/DMS-Backend pull request #432
Opened 2023-04-09 13:58 UTC by tedsoftj1123

## 작업 내용 설명
- [x] sentry 로깅 설정

## 주요 변경 사항
- ExeptionFilter

## 결과물
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/52336493/230777004-0b7800b0-963c-4d09-8935-d8376e204361.png">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #425

2023-04-09 22:17 UTC, rlaisqls requested changes

2023-04-09 22:17 UTC, rlaisqls commented on dms-infrastructure/build.gradle.kts
> +    implementation("io.sentry:sentry-spring-boot-starter:6.2.1")
Dependencies랑 DependencyVersions에 추가해주세요.
그리고 주석명도 sentry 말고 logging으로 바꿔주세여

2023-04-09 23:17 UTC, softpeanut requested changes

2023-04-09 23:17 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
여기도 추가해주세요

2023-04-09 23:19 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
DmsException도 sentry에 찍어야하나요? 찍어야하는 이유가 뭔가요?

2023-04-10 01:58 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
fileter에서 발생한 것도 예외로 봐야하지 않을까요

2023-04-10 02:11 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
`InternalServerErrorException`을 직접 던지는 경우도 잡아야할 것 같긴 하네요.
아니면 `UserNotFoundException` 같은 일반적인 에러도 추가하자는 말씀이신가요?

2023-04-10 02:32 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
일반적인 에러를 잡는건 아래에 있는 부분에서 잡힐 것 같고,
모든 에러를 다 로깅하는 것도 괜찮을 것 같아요

2023-04-10 02:32 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
추후 어느 부분에서 에러를 많이 일으키는지 파악하고, 어떻게 개선할지 고민해볼 수 있을 것 같아요

2023-04-10 02:33 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
>              errorToJson(e.errorProperty, response)
그런 목적이라면 좋네용

2023-04-10 06:02 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
> +                is DmsException -> {
여긴 빠졌네요

2023-04-10 06:04 UTC, jeongyoon05 commented on dms-core/src/test/kotlin/team/aliens/dms/domain/point/model/PointHistoryTests.kt
> +import org.junit.jupiter.api.Test
이건뭐죠..?

2023-04-10 06:17 UTC, tedsoftj1123 commented on dms-core/src/test/kotlin/team/aliens/dms/domain/point/model/PointHistoryTests.kt
> +import org.junit.jupiter.api.Test
음.. 저 테스트 import가 다 빠져있는거같은데 rebase해서 해결하겠습니다

2023-04-10 06:18 UTC, tedsoftj1123 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
> +                is DmsException -> {
마지막 커밋이 해결한 커밋입니다

2023-04-10 07:40 UTC, softpeanut approved these changes

2023-04-10 07:41 UTC, rlaisqls approved these changes

2023-04-10 14:08 UTC, merged