merge: (#431) web request 프로퍼티 non-null로 변경
team-aliens/DMS-Backend pull request #434
Opened 2023-04-09 15:23 UTC by alsdl0629

## 작업 내용 설명
- [X] web request 프로퍼티 non-null로 변경

## 주요 변경 사항
- WebAdapters
- WebRequest

## 결과물
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/103026813/230781478-c99d32c8-9f45-43ca-8956-3aea31094021.png">

## 체크리스트
- [X] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #431

2023-04-09 15:49 UTC, alsdl0629 commented
Multipartfile 보낼 때 아무것도 안 보내면 500 에러가 터져서 Multipartfile 받는 부분은 변경하지 않았는데 어떻게 하는 게 좋을까요?
### nullable일 때
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/103026813/230782494-175639ab-84fb-422b-8a9e-e0863c355f5d.png">

### non-null일 때
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/103026813/230781977-2e72fb59-b77d-42a7-b1f0-1dcac6d0e943.png">
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/103026813/230782194-a26b0894-e7a2-414a-9faf-4d4e6ab85923.png">

2023-04-09 22:19 UTC, rlaisqls requested changes

2023-04-09 22:19 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
> +    fun getAllPointOptions(@RequestParam(required = false) keyword: String): QueryPointOptionsResponse {
required false 붙은건 nullable이어야 할 것 같아요

2023-04-09 22:25 UTC, rlaisqls reviewed
500 막기 위해서라면 multipart는 놔둬도 괜찮을 것 같아요. 그리고 이거 not null로 바꾼 이유랑 multipart만 nullable로 둔 이유에 대해서 문서 하나만 간단하게 작성해주실 수 있나요?

2023-04-09 22:25 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt
> +        val typeId: UUID,
여기도 마찬가지로 nullable이어야할 것 같아요

2023-04-09 22:25 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
> +        val typeId: UUID,
여기도..

2023-04-10 13:38 UTC, rlaisqls requested changes

2023-04-10 13:38 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
이것도 nullable이어야해요

2023-04-10 13:42 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
> +        @RequestPart @NotNull file: MultipartFile?,
자습실 출력은 일반 출력이랑 템플릿 업로드 후 출력 두가지 있어서 얜 nullable이 맞아여

2023-04-11 23:46 UTC, softpeanut approved these changes

2023-04-12 04:11 UTC, rlaisqls approved these changes

2023-04-12 10:38 UTC, merged