merge: (#512) 내 잔류 신청항목 보기 api 수정
team-aliens/DMS-Backend pull request #513
Opened 2023-06-01 14:23 UTC by alsdl0629

## 작업 내용 설명
- [x] 내 잔류 신청항목 보기 api 수정
- [x] aOS 개발자님의 요구

## 주요 변경 사항
- 잔류 옵션 UUID 반환

## 결과물
<img width="1072" alt="스크린샷 2023-06-01 오후 11 21 52" src="https://github.com/team-aliens/DMS-Backend/assets/103026813/04698bc2-8f20-42c6-b6fe-130f041a1a6f">

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #512

2023-06-01 14:37 UTC, tedsoftj1123 approved these changes

2023-06-01 22:15 UTC, rlaisqls requested changes

2023-06-01 22:15 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
> +        )
이거 CurrentAppliedRemainOption에 대해서 객체를 따로 파는게 아니라, 지금 innerclass로 있는 RemainElement를 RemainResponse로 바꿔서 id랑 title 제외한 나머지 필드는 nullable로 두고 ofDetail of로 구분해야하지 않을까요?
이전에는 id만 있어서 분리해도 괜찮다고 생각했는데 정보 추가할거면 병합하는게 저희 코드의 방향성에 맞는 것 같아요.

아래는 비슷한 구조로 되어있는 [studyRoomResponse](https://github.com/team-aliens/DMS-Backend/blob/develop/dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudyRoomResponse.kt) 코드 일부입니다
```kotlin
    companion object {
        fun of(studyRoom: StudyRoom) = studyRoom.run {
            StudyRoomResponse(
                id = id,
                floor = floor,
                name = name,
                availableSex = availableSex,
                availableGrade = availableGrade,
                totalAvailableSeat = availableHeadcount
            )
        }

        fun ofDetail(studyRoom: StudyRoom) = studyRoom.run {
            of(this).copy(
                eastDescription = studyRoom.eastDescription,
                westDescription = studyRoom.westDescription,
                southDescription = studyRoom.southDescription,
                northDescription = studyRoom.northDescription,
                totalWidthSize = studyRoom.heightSize,
                totalHeightSize = studyRoom.widthSize
            )
        }
    }
```

2023-06-02 00:55 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
> +        )
동의합니다잇

2023-06-02 00:55 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
> +        )
저 부분은 리팩토링이 완료되면 추후 개선해야될 부분이고, 앞으로는 합쳐나가는 방향이 맞는 것 같아요!

2023-06-02 06:45 UTC, rlaisqls requested changes

2023-06-02 06:45 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/dto/RemainResponse.kt
> +        fun of(remainOptionId: UUID, title: String) = RemainOptionResponse(
파라미터를 각각 받지 말고 RemainOption domain model로 받아서 처리해주세요

2023-06-02 06:45 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
> +        val student = studentService.getCurrentStudent()
이거 admin에서도 쓰는 api 아닌가요? CustomDetails에 authority를 따로 저장해서 remainService에 `getRemainStatusByUserId`를 하나 만들고 거기서 권한 판별해서 가져오는게.. 지금으로썬 최선일 것 같은데요

2023-06-02 06:45 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/remain/dto/RemainResponse.kt
> +                RemainOptionResponse.of(it.id, it.title).copy(
이렇게 쓰지 말고 RemainOptionResponse 안에 DetailOf 메서드를 정의해주세요

2023-06-02 11:51 UTC, rlaisqls approved these changes

2023-06-02 13:57 UTC, merged