merge: (#521) FCM 등록 및 발송 구현
team-aliens/DMS-Backend pull request #522
Opened 2023-06-13 12:17 UTC by rlaisqls

## 작업 내용 설명
- [x] fcm device token 등록 api
- [x] fcm topic 구독 api
- [x] spring event 사용하여 fcm 알림 전송 구현
- [x] 공지 등록시 알림 전송 추가

## 주요 변경 사항
- PR 내용이 많아 DB 저장 부분은 다음에 구현 예정입니다.

## 결과물

## 체크리스트
- [x] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #521

2023-06-14 00:15 UTC, softpeanut requested changes

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        )
이건 코드와는 별개로, 이렇게 하는 거면 사용자에게 동의는 구하고 알림을 켜는 거죠?

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        val notificationToken = this.getDeviceTokenByUserId(userId)
여기도 용어 통일이 필요해보입니다.
getDeviceToken인데 변수 이름은 notificationToken이니 로직이 이해가 되지 않습니다.

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        val notificationToken = this.getDeviceTokenByUserId(userId)
여기도

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        val notificationToken = this.getDeviceTokenByUserId(userId)
여기도

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        val notificationToken = this.getDeviceTokenByUserId(userId)
여기도

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +    override fun updateSubscribes(userId: UUID, topicSubscribes: List<Pair<Topic, Boolean>>) {
매개변수 이름을 topicSubscribes -> `topicsToSubscribe`와 같이 하는게 더 직관적일 것 같아요

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        }
코드를 통해 이해한 바로는 topic들을 isSubscribe에 따라 구독하거나, 구독을 취소하거나 인데 이렇게 하면 불필요한 구독 / 구독 취소가 일어날 것 같아요.

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/UpdateTopicSubscribesUseCase.kt
> +    fun execute(topicSubscribes: List<Pair<Topic, Boolean>>) {
여기도 매개변수 이름 변경 하는게 좋을 것 같아요

2023-06-14 00:15 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/service/event/EventService.kt
> +}
Event를 통해 분리하는 이유가 있나요?

2023-06-14 00:15 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
> +    fun subscribeTopic(@RequestParam @NotNull topic: Topic) {
이거 왜 body로 안받아?

2023-06-14 00:15 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
> +            topicSubscribes = request.topicSubscribes.map{it.toPair()}
여기도 왜 body로 안받아?

2023-06-14 02:40 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/service/event/EventService.kt
> +}
Event를 사용한 이유는 비즈니스 로직에 대한 트랜잭션과 FCM 전송에 대한 트랜잭션을 따로 두어야한다고 생각했기 때문입니다. 만약 알림 전송이 실패한다고 하더라도 비즈니스 로직에 대한 트랜잭션에 대한 영향을 주어선 안되니 Event를 사용해 분리해주었습니다. 필요한 경우엔 전송 실패에 대한 처리를 따로 해줄 수도 있을 것 같습니다.

2023-06-14 02:50 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventHandler.kt
> +    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
음.. @Transactional은 트랜잭션을 따로 시작는걸 생각하고 붙였는데 없어도 상관없습니다.
@EventListener도 없어도 되는 어노테이션입니다. 불필요한 어노테이션들 삭제해놓겠습니다.

2023-06-14 02:54 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/event/Events.kt
> +) : ApplicationEvent(notification)
토픽 전체에 뿌리는게 아니라 특정 사람들에게만 보내고 싶을땐 토큰으로 특정해서 전송해야합니다. 
해당 부분에 대한 구현을 안 해놓았었는데 추가했습니다 f656908f5609393034b43c2f30c021026b46c5e8

2023-06-14 03:21 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        )
광고성 푸시가 아니라서 사전 동의는 없고, topic subscribe를 통해서 on/off는 가능하도록 구현할 예정입니다.

2023-06-14 03:23 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        }
하지만 해당 deviceToken이 topic을 구독하고 있는지 아닌지를 fcm을 통해 확인할 수 있는 방법이 없어 개선이 불가능합니다. 설정 정보를 app에서 저장해놓을 수는 있기 때문에 설정을 수정한 topic에 대해서만 요청을 보내는 식으로 최적화할 것 같습니다.

2023-06-14 03:23 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
> +            topicSubscribes = request.topicSubscribes.map{it.toPair()}
이 부분은 실수인 것 같습니다..

2023-06-14 03:25 UTC, rlaisqls commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
> +    fun subscribeTopic(@RequestParam @NotNull topic: Topic) {
특별한 이유가 있는 것은 아니고 받아야하는 정보가 하나밖에 없어서 queryParam으로 만들어주었습니다.

2023-06-14 04:41 UTC, softpeanut commented on dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
> +    fun subscribeTopic(@RequestParam @NotNull topic: Topic) {
해당 정보를 사용해서 필터링이나 검색하는 것이 아닌 저장하기 때문에 body로 받는게 더 좋을 것 같아요

2023-06-14 04:42 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        }
어떤 걸 구독했는지 데이터베이스에서 관리하도록 할 수도 있습니다

2023-06-14 04:44 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/service/event/EventService.kt
> +}
event publisher에서 notification service를 호출하도록 하는게 통일성 있을 것 같아요
바로 port를 호출하면 새로운 관리 포인트가 생기기 때문에 유지보수에 헷갈릴 수 있을 것 같습니다

2023-06-14 05:15 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/service/event/EventService.kt
> +}
혹시 `NotificationEventHandler`에서 port의 `sendMessage`, `sendByTopic`을 호출하는 것에 대해 말씀하시는건가요?
만약 그렇다면, 그 부분에선 port에 의존하는게 더 적절한 것 같아요. 관리포인트를 줄이는 관점에선 service에 로직을 두는 게 맞는 방법이지만, 만약에 fcm 전송하는걸 모두 event로 분리할거라면 그 동작을 수행하고 그에 따른 다른 로직들을 정의하는 클래스는 usecase에서도 같이 사용할 수 있는 service가 아니라 eventHandler여야 한다고 생각합니다.

2023-06-14 05:23 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
이거 이름을 NotificationEventPort로 변경하는게 더 좋을 것 같아요

2023-06-14 05:23 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt
> +class EventAdapter(
이 부분도 NotificationEventPublisher로 이름을 변경하는게 좋을 것 같아요

2023-06-14 22:20 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
이 EventPort를 Notification용으로만 사용하지 않을 것 같아요. Event를 발행해야하는 다른 용도가 생겼을때 그것에 대한 EventAdapter와 Port를 분리하는건 관리의 복잡도만 가중시킨다고 생각합니다. 
반면에 Handler는 용도별로 필요한 의존성이 다르고, 컴포넌트별로 Transaction 등을 따로 설정해줄 수도 있을 것 같아서 분리해놓았습니다.

2023-06-14 22:37 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
> +        }
그것도 다음 PR에서 설계하는 과정 더 거쳐서 구현해보겠습니다

2023-06-15 00:22 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
Notification을 발송시키는 것은 다른 이벤트 와는 다른 작업인 것 같아요.
다른 이벤트들은 하나로 묶어도 괜찮지만, 알림은 추후에 모듈 또는 서버로 분리할 수 있기 때문에 따로 묶는게 좋을 것 같아요.

2023-06-15 00:25 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
다른 모듈이나 서버로 분리한다고 하더라도 Event를 Publish하는 작업은 동일하게 가져가고, 실제로 전송하거나 다른 모듈과 연결하는 부분은 EventListener만 수정해서 처리하면 되지 않나요?

2023-06-15 00:37 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
분리하게 되면 같은 port, adapter를 가져갈 수 없어요.

2023-06-15 00:44 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
모듈이나 서버를 분리한다면 같은 port, adapter + 다른 EventListener를 사용하면 될 것 같아요.
실제 알림발송 부분은 어차피 eventListener로 분리되어 있기 때문에 notification 모듈 분리와 event port, adapter를 분리하는건 다른 차원인 것 같습니다

2023-06-15 01:11 UTC, softpeanut commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
제가 말하고자 하는 내용은 EventPort, EventAdapter로 모든 이벤트를 발행하는 부분(eventPublisher 호출)을 묶게 되면 추후에 각 도메인 간의 결합도가 높아질 것 같아요.
도메인 별로 EventPort,Adapter를 분리하고 알림 또한 분리하는게 저희가 추구하는 방향과 맞는 것 같아요

2023-06-15 01:28 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
> +interface EventPort {
Adapter를 분리하는건 코드 관리 측면에서 복잡도를 너무 가중시키는 것 같고,  도메인간의 결합 문제가 걱정된다면 이전에 사용하던 방식처럼 포트만 분리시키는건 어떨까요?

```kotlin
interface NotificationEventPort {
    fun publishNotification(deviceToken: String, notification: Notification)
    fun publishNotificationToAll(notification: Notification)
}

interface EventPort : NotificationEventPort
```

2023-06-16 04:51 UTC, softpeanut commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt
> +    override fun publishNotificationToAll(
이거 함수를 topic을 구독하고 있는 사람들한테만 보낸다는 의미가 들어가도록 바꿔야될 것 같아

2023-06-16 04:51 UTC, softpeanut commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/DeviceTokenJpaRepository.kt
> +    fun queryByUserId(userId: UUID): DeviceTokenJpaEntity?
이건 이름이 왜 query~~ 인가요?

2023-06-16 05:01 UTC, rlaisqls commented
커멘트 달아주신 사항 따라 반영 완료했습니다 @softpeanut 
- saveNotice 이후에 알림 발송하도록 수정
- 컨벤션에 맞지 않거나 직관적이지 않은 메서드명 개선
- 실수로 커밋한 printStackTrace 삭제

2023-06-16 05:12 UTC, softpeanut approved these changes
LGTM

2023-06-16 05:13 UTC, softpeanut commented
DB 설계 관련 pr 올릴 때에는 설계 사진과 이유도 함께 첨부하면 좋을 것 같아여

2023-06-16 11:27 UTC, alsdl0629 approved these changes

2023-06-16 13:09 UTC, merged