merge: (#538) 외출 신청 & 외출 타입 엔티티 세팅
team-aliens/DMS-Backend pull request #541
Opened 2024-02-02 07:17 UTC by ilyoil2

## 작업 내용 설명
- [ ] 외출 신청 persistence, model, mapper
- [ ] 외출 타입 persistence, model, mapper

## 주요 변경 사항

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #

2024-02-02 09:41 UTC, alsdl0629 requested changes
엔티티 세팅할 때 local에서 만든 테이블 ddl 정보 pr 템플릿 부분에 보여주면 좋을 거 같아
그리고 관련 이슈에 #538 이슈 번호 명시하면 pr 머지할 때 issue도 자동으로 닫혀

2024-02-02 09:41 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingType.kt
> +    val outingType: String,
outingType.outingType 어색할거같은데 title로 바꾸는거 어때?

2024-02-02 09:41 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingType.kt
> +)
```suggestion
    override val schoolId: UUID,

) : SchoolIdDomain

```
이렇게 변경해줘

2024-02-02 09:41 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingTypeJpaEntity.kt
> +import javax.persistence.*
기존 코드처럼 import에서 * 사용하지 않고 하나씩 명시하면 좋을 거 같아

2024-02-02 09:41 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingTypeJpaEntity.kt
> +    )
```suggestion
)

```

2024-02-02 09:46 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingType.kt
> +    val outingType: String,
넵

2024-02-02 11:34 UTC, rlaisqls reviewed
빌드 깨지는 거 확인해주시고, gradlew에 있는 ktlint 명령어 한 번 돌려주세요!

2024-02-02 11:34 UTC, rlaisqls commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingTypeMapper.kt
> +        val school = schoolRepository.findByIdOrNull(domain.schoolId)
school이 null인 경우에 Custom Exception 던지는 게 안전할 것 같아요

2024-02-02 13:19 UTC, tedsoftj1123 reviewed
rebase한번 해야할듯

2024-02-03 13:15 UTC, rlaisqls commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingTypeMapper.kt
> +        val school = schoolRepository.findByIdOrNull(domain.schoolId) ?: throw OutingNotFoundException
다른 엔티티에서는 엔티티 조회에서 매핑된 school을 못 찾는 경우에 SchoolNotFound를 던지도록 되어있어서 통일해주시면 좋을 것 같아요

2024-02-04 07:30 UTC, alsdl0629 requested changes

2024-02-04 07:30 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
> +    val title: String,
```suggestion
    val outingTypeTile: String,

```
어때?

2024-02-04 07:30 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
> +    val title: OutingTypeJpaEntity?,
```suggestion
        JoinColumn(name = "outing_type_title", referencedColumnName = "title", nullable = false),
        JoinColumn(name = "outing_type_school_id", referencedColumnName = "school_id", columnDefinition = "BINARY(16)", nullable = false),
    )
    val outingType: OutingTypeJpaEntity?,

```

2024-02-04 07:30 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
> +    val school: SchoolJpaEntity?
이건 없애도 될 거 같아

2024-02-04 07:30 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/OutingTypeJpaRepository.kt
> +interface OutingTypeJpaRepository : CrudRepository<OutingTypeJpaEntity, UUID> {
```suggestion
interface OutingTypeJpaRepository : CrudRepository<OutingTypeJpaEntity, OutingTypeJpaEntityId> {

```

2024-02-04 07:30 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
> +class OutingApplicationMapper(
```
class OutingApplicationMapper(
    private val outingTypeJpaRepository: OutingTypeJpaRepository,
    private val studentRepository: StudentJpaRepository,
) : GenericMapper<OutingApplication, OutingApplicationJpaEntity> {

    override fun toDomain(entity: OutingApplicationJpaEntity?): OutingApplication? {
        return entity?.let {
            OutingApplication(
                id = it.id!!,
                studentId = it.student!!.id!!,
                createdAt = it.createdAt,
                outAt = it.outAt,
                outingTime = it.outingTime,
                arrivalTime = it.arrivalTime,
                status = it.status,
                reason = it.reason,
                destination = it.destination,
                title = it.outingType!!.id.title,
                schoolId = it.outingType!!.id.schoolId
            )
        }
    }

    override fun toEntity(domain: OutingApplication): OutingApplicationJpaEntity {
        val id = OutingTypeJpaEntityId(
            title = domain.title,
            schoolId = domain.schoolId
        )
        val outingType = outingTypeJpaRepository.findByIdOrNull(id) // 예외처리
        val student = studentRepository.findByIdOrNull(domain.studentId) // 예외처리

        return OutingApplicationJpaEntity(
            id = domain.id,
            student = student,
            createdAt = domain.createdAt,
            outAt = domain.outAt,
            outingTime = domain.outingTime,
            arrivalTime = domain.arrivalTime,
            status = domain.status,
            reason = domain.reason,
            destination = domain.destination,
            outingType = outingType
        )
    }
}
```
이렇게 바꿔야될 거 같아

2024-02-04 11:16 UTC, rlaisqls commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
> +    val school: SchoolJpaEntity?
테이블 매핑을 없애도 된다는 말씀이신가요? 없애도 된다고 생각하시는 이유는 뭔가용

2024-02-04 12:11 UTC, tedsoftj1123 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
> +class OutingApplicationMapper(
기존 코드 보니까 연관된 엔티티 못찾는거에 대해선 Mapper에선 따로 예외 안던지고 core쪽에서 처리하게 되있는 것 같은데 얘도 통일 하는게 좋지 않을까요?

2024-02-04 12:41 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
> +class OutingApplicationMapper(
1. OutingApplicationJpaEntity가 직접적으로 school을 참조하지 않도록 변경
2. OutingTypeJpaEntity를 OutingTypeJpaEntityId를 통해 가져오도록 변경

2024-02-04 12:42 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
> +    val school: SchoolJpaEntity?
OutingTypeJpaEntity를 통해 school을 참조할 수 있는데 여기서 한 번 더 선언하는 게 불필요하다고 느꼈습니다.

2024-02-05 06:32 UTC, alsdl0629 approved these changes

2024-02-05 11:06 UTC, merged