merge: 상벌점 엑셀 수정
team-aliens/DMS-Backend pull request #585
Opened 2024-03-18 08:23 UTC by ilyoil2

## 작업 내용 설명
- [ ] 부여 취소된 상벌점 내역은 조회 X
- [ ] 조회시 엑셀 넓이 변경
- [ ] 태그 조회 수정

## 주요 변경 사항
- 
- 

## 결과물
![image](https://github.com/team-aliens/DMS-Backend/assets/127661235/14bfe86c-60c6-451f-8bb2-59c1fed41a40)

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #584

2024-03-18 09:07 UTC, rlaisqls requested changes

2024-03-18 09:07 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
> +        sheet.setColumnWidth(7, 15 * 256)
이렇게 추가하면 액셀을 출력하는 모든 API가 영향을 받을 것 같아요..
createExcelSheet 함수에 callback 함수를 파라미터로 넣어서 스타일을 선택적으로 적용할 수 있게 하는건 어떨까요?

#### 예시

파라미터 넘기는 부분
```kotlin
        return createExcelSheet(
            attributes = attributes,
            datasList = studentsList,
            applyToSheet = { sheet ->
                  sheet.setColumnWidth(1, 7 * 256)
                  sheet.setColumnWidth(2, 5 * 256)
                  sheet.setColumnWidth(3, 5 * 256)
                  sheet.setColumnWidth(4, 45 * 256)
                  sheet.setColumnWidth(5, 45 * 256)
                  sheet.setColumnWidth(6, 10 * 256)
                  sheet.setColumnWidth(7, 15 * 256)
            }
        )
```

callback 함수 사용
```kotlin
    private fun createExcelSheet(
        attributes: List<String>,
        datasList: List<List<String?>>,
        applyToSheet: Consumer<Sheet> = { _ -> return }
    ): ByteArray {
        ...
        applyToSheet.accept(sheet)
    }
```

2024-03-20 06:18 UTC, rlaisqls reviewed
빌드 깨지는거 한 번 확인해주세요!

2024-03-20 06:18 UTC, rlaisqls commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
> +
불필요한 빈 줄 없애주세욥

2024-03-20 13:31 UTC, rlaisqls commented
테스트 깨지는 것도 확인해주세요!

2024-03-21 02:34 UTC, parkuiery approved these changes

2024-03-21 04:29 UTC, rlaisqls approved these changes

2024-03-21 04:29 UTC, merged