merge: (#572) 외출 내역 상세보기
team-aliens/DMS-Backend pull request #597
Opened 2024-03-27 09:51 UTC by ilyoil2

## 작업 내용 설명
- [ ] 
- [ ] 

## 주요 변경 사항
- 
- 

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #

2024-03-27 10:47 UTC, alsdl0629 requested changes

2024-03-27 10:47 UTC, alsdl0629 commented on dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
> +                .requestMatchers(HttpMethod.GET, "/outings/history/{outing-application-id}").permitAll()
권한 설정 해야될 것 같아요

2024-03-27 10:47 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingHistoryDetailsUseCase.kt
> +
줄 삭제해주세요

2024-03-27 10:47 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
> +    fun queryOutingCompanionsById(applicationId: UUID): List<OutingCompanionDetailsVO>
```suggestion
    fun queryOutingCompanionsByOutingApplicationId(outingApplicationId: UUID): List<OutingCompanionDetailsVO>
```

2024-03-27 10:47 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
> +    fun getOutingCompanionsById(outingApplicationId: UUID): List<OutingCompanionDetailsVO>
여기도 고쳐주세요

2024-03-27 10:47 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryStudentOutingHistoryVO.kt
> +class QueryStudentOutingHistoryVO @QueryProjection constructor(
```suggestion
class QueryOutingCompanionDetailsVO @QueryProjection constructor(
```
이런식으로 다른 VO 네이밍과 통일하면 좋을 것 같아요.

2024-03-27 10:47 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
> +    override fun queryOutingCompanionsById(applicationId: UUID): List<OutingCompanionDetailsVO> {
```suggestion
    override fun queryOutingCompanionsById(outingApplicationId: UUID): List<OutingCompanionDetailsVO> {

```

2024-03-27 10:47 UTC, alsdl0629 commented on dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
> +            .from(studentJpaEntity)
```suggestion
            .from(outingCompanionJpaEntity)
```
이렇게 바꾸면 좋을 것 같아요

2024-03-27 10:47 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionDetailsVO>?
이걸 그대로 반환하면 명세랑 다르게 나오지 않나요?

2024-03-27 12:09 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionDetailsVO>?
쓸데 없는 정보들을 어떻게 없앨까요..

2024-03-27 12:38 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionDetailsVO>?
StudentDetailsResponse 재사용하면 될 것 같아요.

2024-03-28 11:21 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionDetailsVO>?
studentDetailsResponse는 profile 사진을 넣어줘야해서 새로 response만들었어요

2024-03-28 13:02 UTC, alsdl0629 requested changes

2024-03-28 14:33 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionsResponse>?
동행자는 없을 수도 있으니까 nullable이 맞을 것 같습니다
수정하겠습니다

2024-03-28 14:51 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val students: List<OutingCompanionsResponse>?
그리고 outAt -> outingDate로 바꿨는데 flyway에서 바꿔야하지 않나요?

2024-03-29 02:17 UTC, alsdl0629 approved these changes

2024-03-29 02:17 UTC, alsdl0629 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
> +    val reason: String?,
```suggestion
    @field:JsonInclude(JsonInclude.Include.ALWAYS)
    val reason: String?,
```
null일 때도 반환되도록 변경해주세요.

2024-03-29 03:09 UTC, merged