feat: (#602) 벌점 태그 자동 부여 스케줄러 추가
team-aliens/DMS-Backend pull request #607
Opened 2024-04-12 08:03 UTC by zios0707

## 작업 내용 설명
- [ ] 벌점 태그를 자동으로 부여 api 추가

## 주요 변경 사항
- 

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #602

2024-04-12 08:20 UTC, 4mjeo commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
> +
다른 메서드랑 통일성 있게 블록 사용하면 좋을 것 같아요

2024-04-12 08:27 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +        studentService.getAllStudentsByName("").forEach { student ->
forEach 사용하면 tag 저장 쿼리가 각각 실행되어서 실행 시간이 길어질 수 있을 것 같아요.
`mapNotNull` 등을 활용해서 저장해야하는 태그의 목록을 구한 후 한 번에 쿼리를 날리도록 하는건 어떨까요?

2024-04-12 08:27 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +            )
점수를 파라미터로 넣어서 경고 단계를 구하는거라면 더욱 명시적인 함수명을 사용하는 것이 좋을 것 같아요.
그리고 학생 정보 가져오는 쿼리랑 이 쿼리를 합쳐서 사용할 수 있는 방법이 없을지 고민해보시면 좋을 것 같아요..

2024-04-12 08:27 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
경고 태그인지 여부를 이름을 통해 판별하고 있는 것으로 보이는데, 이것도 더 명시적인 함수명이면 좋을 것 같아요.
경고 태그가 아닌 다른 태그가 있을 때 null을 반환해서 처리한다는 것도 코드를 자세히 보지 않으면 한 번에 이해하기 힘들 수 있을 것 같네요. 더 직관적인 방법은 없을까요?

2024-04-12 08:27 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
여기도 마찬가지로 태그 조회 쿼리를 따로 날리는 형태라 성능 저하가 있을 수 있을 것 같아요

2024-04-12 08:29 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
> +
다른 서비스 Impl 메서드에서는 블록 지정하지 않는 경우도 많아서 ([예시](https://github.com/team-aliens/DMS-Backend/blob/develop/dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt)) 꼭 수정할 필요는 없어보입니다. (반환값 없는 메서드만 구분을 위해 블록으로 작성하는 암묵적? 규칙이 있었던 것 같아요)

2024-04-12 09:58 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
이건 살짝 애매해서 정확히 처리하기 힘들 것 같아요. 따로 추천하시는 방법 있으실까요?
일단 경고 태그를 이름과 uuid로 `key-value` 에 담아두고 처리해보는 방안을 생각하고 있긴합니다만 괜찮을지 여쭤봐도 될까요

2024-04-12 10:50 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
음 경고 태그 ID를 담아놓은 테이블을 따로 정의한 후 조인해서 가져오는 방법도 있을 것 같아요

2024-04-12 11:15 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
db에서 경고 태그 id를 빠르게 조회할 수 있도록 다시 구조화 하라는 말씀이실까요?

2024-04-12 11:16 UTC, rlaisqls requested changes

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +        fun ofByPoint(warningLevel: Int) = when ((warningLevel - 10) / 5) {
`fromPoint`같은 이름도 괜찮을 것 같아요. 그리고 변수 명도 맞게 바꿔주세용

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            in 6..Int.MAX_VALUE -> THREE_OUT
벌점이 1점이면 1차 경고인가요?

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +        studentService.getAllStudentWithMinusPoint().forEach { (studentId, minusPoint) ->
빈 List에 추가하는 로직이면 `forEach` 말고 `map`이나 `mapNotNull`써주세요

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                tagService.getStudentTagsByStudentId(studentId).stream().forEach { tag ->
학생 태그 목록 조회하는 것도 각 학생별로 따로 날리면 성능 저하 있을 것 같네요
이 부분도 한 쿼리로 묶어주세요

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            else -> null
없는 이름일 때 null로 반환해서 처리하는 것 보다 예외를 throw하고 `try-catch`로 잡는 게 더 명확한 방식인 것 같아요

2024-04-12 11:16 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +    }
이거 이런 식으로 구현하지 말고, 아래처럼 enum에 이름 필드 넣어서 활용하면 더 깔끔하게 사용할 수 있을 것 같아요
```
enum class Color(val rgb: Int) {
    RED(0xFF0000),
    GREEN(0x00FF00),
    BLUE(0x0000FF)
}
```

2024-04-12 11:19 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
1. 경고 태그 테이블 정의 (경고 태그에 해당하는 ID를 row로 수동으로 삽입)
2. 학생의 태그를 가져올때 경고 태그 테이블이랑 inner join해서 조회
이런 방식입니다

2024-04-12 11:23 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
> +                    .map { tag -> WarningTag.of(tagService.getTagById(tag.tagId).name) }
사실 ID를 DB에 저장한다면 name과 단계 순서(단계별 점수)를 Row에 같이 저장하는 것도 가능한 방법일 것 같습니다.

2024-04-12 11:24 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
> +        }
VO로 QueryProjection 해서 쿼리 하나로 묶어주세요 ~~~

2024-04-15 00:42 UTC, rlaisqls commented
@zios0707 수정 사항 반영 언제 가능하신가용?
혹시 이 기능 완료 일정이 어떻게 되나요

2024-04-15 01:55 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            in 6..Int.MAX_VALUE -> THREE_OUT
경고 단계별로 나눈 것입니다

2024-04-15 02:06 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            in 6..Int.MAX_VALUE -> THREE_OUT
경고 단계별로 나눈 거라면 `ofByPoint`라는 함수 명과 맞지 않는 것 같아요.

https://github.com/team-aliens/DMS-Backend/blob/dbb302c28b732719dd9904a2aee72b0cbe6c98c6/dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt#L22

하지만 UseCase에서는 이 함수가 벌점을 기준으로 단계를 판별하는데 사용하고 있어서, '벌점을 입력받았을 때 그에 따른 경고 단계를 반환'하는 함수로 구현을 수정하는 것이 맥락상 적절한 것 같아요.

2024-04-15 02:09 UTC, zios0707 commented
일단 개발하고는 있습니다만 이런 기능 개발은 처음인지라 조금 어렵네요...

2024-04-15 03:31 UTC, rlaisqls commented
혹시 오늘 저녁에 기숙사에서 페어 프로그래밍 하실래요? 
리뷰드린 부분 관련해서 복잡한 부분은 직접 설명드리는 게 나을 것 같아서요!
오늘 어려우시다면 이번주 중에 아무때나 괜찮습니당

2024-04-15 04:14 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            in 6..Int.MAX_VALUE -> THREE_OUT
https://github.com/team-aliens/DMS-Backend/blob/dbb302c28b732719dd9904a2aee72b0cbe6c98c6/dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt#L13

이 부분에서 벌점 인수를 받고 when 문으로 넘어갈 때 값이 처리되어서 괜찮을 것 같습니다.

2024-04-15 04:19 UTC, zios0707 commented
> 혹시 오늘 저녁에 기숙사에서 페어 프로그래밍 하실래요? 리뷰드린 부분 관련해서 복잡한 부분은 직접 설명드리는 게 나을 것 같아서요! 오늘 어려우시다면 이번주 중에 아무때나 괜찮습니당

페어 프로그래밍은 처음 들어보지만 해보면 괜찮을 경험일 것 같네요. 아직 잘 이해하진 못했지만 모쪼록 부탁드리겠습니다.

2024-04-15 05:26 UTC, rlaisqls commented on dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
> +            in 6..Int.MAX_VALUE -> THREE_OUT
아하 죄송해요 제가 그 부분을 보지 못했네요.
경고 단계별 점수 범위를 한 눈에 이해할 수 있도록 이런 식으로 코드를 작성하면 어떨까요?
계산을 통해서 코드를 짧게 만드는 것도 좋지만, 잘못 이해할 여지없이 직관적인 방법이 더 나을 수 있을 것 같아요.

```kotlin
fun ofByPoint(point: Int) = when {
        point >= 35 -> THREE_OUT
        point >= 30 -> TWO_OUT
        point >= 25 -> ONE_OUT
        point >= 20 -> THIRD_WARNING
        point >= 15 -> SECOND_WARNING
        point >= 10 -> FIRST_WARNING
        else -> SAFE
}
```

2024-04-16 10:17 UTC, rlaisqls approved these changes

2024-04-16 14:14 UTC, merged