merge: (#733) 봉사 신청/ 관리 API
team-aliens/DMS-Backend pull request #743
Opened 2024-09-13 04:09 UTC by 4mjeo

## 작업 내용 설명
- [ ] 봉사 신청 및 관리 기능을 만들었습니다.
- [ ] 

## 주요 변경 사항
- 앱 - 봉사 신청
 - 신청, 신청 취소, 신청 가능 봉사활동 목록 조회, 신청 내역 조회
- 어드민 - 봉사 활동 관리
 - 봉사 추가, 수정, 삭제, 리스트 조회, 봉사 신청 학생 조회, 신청 승인/거절, 봉사 별 현황 조회

## 결과물

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #733

2024-09-13 04:19 UTC, zios0707 requested changes

2024-09-13 05:04 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
> +                gradeCondition = volunteer.gradeCondition
봉사 엔티티에 gradeCondition 와 sexCondition 보다 더 좋은 네이밍은 없을까요?
조건이라는 의미로 했다해도 좀 가독성이 떨어질 것 같아요
availableGender 나 allowedGender가 더 좋을듯 싶어요

2024-09-13 05:06 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/exception/VolunteerErrorCode.kt
> +
❗sequence를 2로 바꿔주세요

2024-09-14 07:45 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryCurrentVolunteerApplicantsUseCase.kt
> +        val currentApplicantsGroup = volunteerService.getAllApplicantsBySchoolIdGroupByVolunteer(schoolId)
❓보통 currentApplicants로 하지 않나요? Group을 붙이신 특별한 이유가 있을까요?

2024-09-14 07:45 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
> +        return QueryMyVolunteerApplicationResponse.of(volunteerApplications, volunteers)
💊이거 한 줄씩 띄워져 있는거 왤케 불편하지

```
@ReadOnlyUseCase
class QueryMyVolunteerApplicationUseCase(
    private val volunteerService: VolunteerService,
    private val studentService: StudentService
) {

    fun execute(): QueryMyVolunteerApplicationResponse {
        val student = studentService.getCurrentStudent()

        val volunteerApplications = volunteerService.getVolunteerApplicationsByStudentId(student.id)
        val volunteers = volunteerService.getAllVolunteers()

        return QueryMyVolunteerApplicationResponse.of(volunteerApplications, volunteers)
    }
}

```
매개변수로 넣어지는 값들은 붙이는게 어때요?

2024-09-14 07:46 UTC, ilyoil2 commented
@zios0707 @4mjeo 봉사신청에 있는 점수가 score ~ optinalScore 맞나요?

2024-09-14 08:17 UTC, 4mjeo commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
> +        return QueryMyVolunteerApplicationResponse.of(volunteerApplications, volunteers)
student 까지 같이 붙이나요??

2024-09-14 15:54 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryCurrentVolunteerApplicantsUseCase.kt
> +        val currentApplicantsGroup = volunteerService.getAllApplicantsBySchoolIdGroupByVolunteer(schoolId)
VO 객체 보시면 Key 는 봉사 활동으로 되어있고 value 는 봉사신청자VO 리스트로 되어있어요. 그래서 그룹이라고 명시해줬습니다.

2024-09-14 15:59 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
> +        val volunteers = volunteerService.getAllVolunteers()
쿼리를 하나로 합치면 트랜잭션 생성이 한번으로 끝나서 괜찮을 것 같습니다만 어떻게 생각하시나요?

2024-09-14 16:01 UTC, zios0707 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
> +        return QueryMyVolunteerApplicationResponse.of(volunteerApplications, volunteers)
쿼리를 하나로 붙이면 트랜잭션도 줄어들고 getAllVolunteer 로 갖고오는 리소스량이 줄어서 괜찮을 것 같습니다.
앞선 문제도 해결 될 것 같고요

2024-09-14 16:03 UTC, zios0707 commented
@ilyoil2 score ~ optionalScore + score 입니다.

2024-09-14 16:04 UTC, zios0707 commented
> @zios0707 @4mjeo 봉사신청에 있는 점수가 score ~ optinalScore 맞나요?

score ~ optionalScore + score 입니다.

2024-09-15 05:36 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryMyVolunteerApplicationUseCase.kt
> +        return QueryMyVolunteerApplicationResponse.of(volunteerApplications, volunteers)
쿼리문 하나로 하는게 확실히 좋을듯 지금 response에서 조건문 달고 찾는게 안 좋아보여요
조회문에서 다 처리해서 넘겨주는게 효율적일듯
![image](https://github.com/user-attachments/assets/6dc86295-b445-4109-872a-82e1e5d4b2a7)

2024-09-15 05:37 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
> +                        VolunteerApplicationResponse.of(application, volunteer)
지금 response에서 조건문 달고 찾는게 안 좋아보여요 현욱이가 말한대로 쿼리문 하나로 하고 그걸 response에 넘겨주는게 더 효울적일듯

2024-09-15 08:55 UTC, 4mjeo commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
> +                        VolunteerApplicationResponse.of(application, volunteer)
좋습니당 ~~

2024-09-15 16:36 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryAvailableVolunteersUseCase.kt
> +
`        val availableVolunteers = volunteerService.getVolunteerByStudentId(student.id)
`

2024-09-15 16:40 UTC, ilyoil2 commented on dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerServiceImpl.kt
> +        queryVolunteerApplicationPort.queryVolunteerApplicationsByStudentId(studentId)
❗이 함수가 지금 사용되는 곳이 없어보여요

2024-09-19 08:08 UTC, ilyoil2 approved these changes

2024-09-19 10:50 UTC, merged